### ISSUE TITLE
wpt lint broken?

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#11320]
As of ee82278e15570e573d87fb80179ff8231b6db61a, `./wpt lint` fails t run on my machine. Not sure what's going on or how to debug it, but here's a stack trace:
```
$ ./wpt lint
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/florian/src/wpt/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/florian/src/wpt/tools/lint/lint.py", line 841, in main
    paths = lint_paths(kwargs, repo_root)
  File "/Users/florian/src/wpt/tools/lint/lint.py", line 799, in lint_paths
    changed_paths = changed_files(wpt_root)
  File "/Users/florian/src/wpt/tools/lint/lint.py", line 780, in changed_files
    revish = testfiles.get_revish(revish=None)
  File "/Users/florian/src/wpt/tools/wpt/testfiles.py", line 320, in get_revish
    revish = "%s..HEAD" % branch_point()
  File "/Users/florian/src/wpt/tools/wpt/testfiles.py", line 81, in branch_point
    assert branch_point or not commit_parents
AssertionError
```

**Comment by frivoal** [comment]
ee82278e15570e573d87fb80179ff8231b6db61a

I've cloned a fresh clean copy of the repo, and now I get this:
```
 $ ./wpt lint
ERROR:root:Git command exited with status 128
ERROR:root:fatal: Not a valid object name origin/master
```

**Comment by jgraham** [comment]
Seems more likely that you called the remote something other than `origin`.

**Comment by frivoal** [comment]
> Did you use the new `web-platform-tests/wpt` repo 

yes. 

> Seems more likely that you called the remote something other than origin.

I have two remotes:
origin: my fork
upstream: `web-platform-tests/wpt`

> How come git doesn't know origin/master
 
As that was a fresh clone from `upstream`, I had yet to push/pull to/from `origin/master`, and doing so fixed it.

So I guess this is fixed. I still don't quite understand what the original problem (before the fresh clone) was, nor why wpt lint needs to fiddle with git, but oh well.

**Comment by gsnedders** [comment]
> why wpt lint needs to fiddle with git

Essentially, to only lint files that have changed. It tries to do it from the nearest branch point, and ultimately falls back to `origin/master`.

That said, the AssertionError definitely shouldn't be hit, so something has gone wrong there.

**Comment by gsnedders** [comment]
(The real fix here is to have more intelligent caching so we can just run the lint on everything and not have to filter what we run it against, but that's a bigger project.)

**Comment by quasicomputational** [comment]
I ran into this after this approximate sequence of steps:

* `git clone -o upstream https://github.com/web-platform-tests/wpt`
* `cd wpt`
* `git remote add origin git@github.com:quasicomputational/wpt.git`
* `git checkout -b foo`
* `./wpt lint`

As noted, pulling from `origin` fixed it.
