### ISSUE TITLE
META.yml: Replace ayg in suggested_reviewers

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11521]
@ayg has not accepted the invite, but appears in a number of META.yml files. Consider removing and adding someone else.

```
$ git grep "  - ayg"
dom/META.yml:  - ayg
editing/META.yml:  - ayg
html/dom/META.yml:  - ayg
html/editing/META.yml:  - ayg
html/infrastructure/META.yml:  - ayg
html/obsolete/META.yml:  - ayg
html/semantics/META.yml:  - ayg
resources/META.yml:  - ayg
selection/META.yml:  - ayg
```
files that include only ayg
```
$ git grep -l "  - ayg" | xargs wc -l | grep "2 "
       2 editing/META.yml
       2 html/dom/META.yml
       2 html/editing/META.yml
       2 html/infrastructure/META.yml
       2 html/obsolete/META.yml
       2 html/semantics/META.yml
       2 selection/META.yml
```
Since html/META.yml exists, the html ones could be removed. That leaves `editing` and `selection`.

**Comment by zcorpan** [comment]
@rniwa can you take `selection`?

@johanneswilm can you take `editing`?

**Comment by foolip** [comment]
I can take html/obsolete, just my kind of thing.

**Comment by foolip** [comment]
html/semantics is very broad, is there really anyone who would be a good reviewer for all of it?

**Comment by zcorpan** [comment]
If nobody steps up, we could split html/semantics in some manner between you, me, @annevk and @domenic. WDYT?

**Comment by foolip** [comment]
Yeah, I'd be fine with with most of html/semantics/embedded-content/. Here are the numbers of files in the directories:
```
2 disabled-elements
2 the-root-element
6 common-idioms
9 edits
15 sections
22 links
26 selectors
27 interactive-elements
44 tabular-data
72 grouping-content
86 document-metadata
88 text-level-semantics
253 forms
495 scripting-1
779 embedded-content
```

**Comment by zcorpan** [comment]
Here are the 5 most recent commit authors for each dir under semantics:
```
semantics zcorpan$ find . -type d -depth 1 | while read line ; do echo $line; git log -r -5 --format="%an %ae" $line ; done
./the-root-element
Robin Berjon robin@berjon.com
./text-level-semantics
Bhagirathi Satpathy bhagirathi.s@samsung.com
Bhagirathi Satpathy bhagirathi.s@samsung.com
Bhagirathi Satpathy bhagirathi.s@samsung.com
Bhagirathi Satpathy bhagirathi.s@samsung.com
Jochen Eisinger jochen@chromium.org
./disabled-elements
Ms2ger ms2ger@gmail.com
Denis Ah-Kang denis@w3.org
Denis Ah-Kang denis@w3.org
Denis Ah-Kang denis@w3.org
Robin Berjon robin@berjon.com
./sections
Robin Berjon robin@berjon.com
./forms
Mike Pennisi mike@mikepennisi.com
Kent Tamura tkent@chromium.org
Anne van Kesteren annevk@annevk.nl
TAMURA, Kent tkent@chromium.org
Rune Lillesveen futhark@chromium.org
./common-idioms
Robin Berjon robin@berjon.com
./scripting-1
Simon Pieters zcorpan@gmail.com
Stephen McGruer smcgruer@chromium.org
Domenic Denicola d@domenic.me
Mike Pennisi mike@mikepennisi.com
Domenic Denicola d@domenic.me
./tabular-data
kaixinjxq xiuqix.jiang@intel.com
tkent@chromium.org tkent@chromium.org
David Grogan dgrogan@chromium.org
Aryeh Gregor ayg@aryeh.name
Jessica Jong jjong@mozilla.com
./links
Anne van Kesteren annevk@annevk.nl
Anne van Kesteren annevk@annevk.nl
charlesvdv charles.vandevoorde@hotmail.be
Boris Zbarsky bzbarsky@mit.edu
Geoffrey Sneddon geoffers@gmail.com
./embedded-content
Ehsan Karamad ekaramad@chromium.org
Simon Pieters zcorpan@gmail.com
Emilio Cobos Álvarez emilio@crisal.io
Emilio Cobos Álvarez emilio@crisal.io
Mike Pennisi mike@mikepennisi.com
./grouping-content
Emilio Cobos Álvarez emilio@crisal.io
Quinten Yearsley qyearsley@google.com
Domenic Denicola d@domenic.me
Petr Gazarov petrgazarov@gmail.com
Domenic Denicola d@domenic.me
./edits
Ms2ger ms2ger@gmail.com
Zhiqiang Zhang zhiqiang.zhang@intel.com
Robin Berjon robin@berjon.com
./interactive-elements
Dave Tapuska dtapuska@chromium.org
Shanmuga Pandi M shanmuga.m@samsung.com
Philip Jägenstedt philip@foolip.org
Shanmuga Pandi M shanmuga.m@samsung.com
Shanmuga Pandi M shanmuga.m@samsung.com
./selectors
Rune Lillesveen rune@opera.com
Rune Lillesveen rune@opera.com
Rune Lillesveen rune@opera.com
rune@opera.com rune@opera.com
rune@opera.com rune@opera.com
./document-metadata
Anthony Ramine n.oxyde@gmail.com
Rakina Zata Amni rakina@chromium.org
Boris Zbarsky bzbarsky@mit.edu
Boris Zbarsky bzbarsky@mit.edu
Boris Zbarsky bzbarsky@mit.edu
```

@foolip can you look into translating these to GitHub usernames?

**Comment by foolip** [comment]
I don't have any special tricks apart from people who work at Google, what I'd do is to look at a commit for each name I don't already recognize, and see what username GitHub attributes it to. Rune is lilles, for example.

**Comment by foolip** [comment]
(Actually a bad example, since I used the Googler lookup tool for that one.)

**Comment by zcorpan** [comment]
Using https://github.com/sindresorhus/github-username-cli
```
$ cat emails.txt | while read line; do echo $line; github-username $line --token=...; done
annevk@annevk.nl
annevk
ayg@aryeh.name
ayg
bhagirathi.s@samsung.com
TypeError: Cannot read property 'login' of null
    at ghGot.then.result (/Users/zcorpan/.nvm/versions/node/v9.2.0/lib/node_modules/github-username-cli/node_modules/github-username/index.js:24:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
bzbarsky@mit.edu
bzbarsky
charles.vandevoorde@hotmail.be
charlesvdv
d@domenic.me
domenic
denis@w3.org
deniak
dgrogan@chromium.org
davidsgrogan
dtapuska@chromium.org
dtapuska
ekaramad@chromium.org
ehsan-karamad
emilio@crisal.io
emilio
futhark@chromium.org
TypeError: Cannot read property 'login' of null
    at ghGot.then.result (/Users/zcorpan/.nvm/versions/node/v9.2.0/lib/node_modules/github-username-cli/node_modules/github-username/index.js:24:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
geoffers@gmail.com
gsnedders
jjong@mozilla.com
jessi3py
jochen@chromium.org
jeisinger
mike@mikepennisi.com
jugglinmike
```
(Got rate-limited here, will post the rest later.)

**Comment by johanneswilm** [comment]
Yes, I can take editing.

**Comment by domenic** [comment]
I can take scripting-1 and probably other stuff. I nominate @tkent-google as reviewer for forms, if he's interested.

**Comment by zcorpan** [comment]
Suggestion based on the above:

Path | Suggested reviewers
---|---
./the-root-element | @darobin
./text-level-semantics | @jeisinger
./disabled-elements | @Ms2ger
./sections | @darobin
./forms | @tkent-google
./common-idioms | @darobin
./scripting-1 | @domenic
./tabular-data | @tkent-google
./links | @annevk
./embedded-content | @foolip @zcorpan
./grouping-content | @domenic
./edits | @Ms2ger
./interactive-elements | @foolip
./selectors | @lilles @zcorpan
./document-metadata | @bzbarsky 

Please respond if you're OK with being asked for review for the above dirs.

**Comment by foolip** [comment]
Those are OK for me.

**Comment by tkent-google** [comment]
I'm fine with forms and tabular-data.

**Comment by Ms2ger** [comment]
Please drop me (unless someone wants to pay me to review those tests).

**Comment by foolip** [comment]
There's only 1 test in disabled-elements and 2 in edits, so maybe we can just leave those without reviewers and let it fall back to html/META.yml.

**Comment by lilles** [comment]
OK.

**Comment by rniwa** [comment]
You can add me as a suggested reviewer for selection tests for sure.

**Comment by bzbarsky** [comment]
I can do document-metadata, I guess.  Availability may be somewhat limited, though...
