### ISSUE TITLE
./wpt install | run not working in MacOS 10.13.5? 

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#11870]
It was working... and now getting the following for install (and similar for ./wpt run)... 

```
./wpt install
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/marcos/temp/web-platform-tests/_venv/bin/python2.7
  Reason: image not found
CRITICAL:tools.wpt.utils:('/Users/marcos/temp/web-platform-tests/_venv/bin/pip', 'install', u'mozdownload') exited with return code -6
CRITICAL:tools.wpt.utils:
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 111, in main
    venv = setup_virtualenv(main_args.venv, props)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 86, in setup_virtualenv
    venv.install(name)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/virtualenv.py", line 50, in install
    call(self.pip_path, "install", *requirements)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/utils.py", line 44, in call
    return subprocess.check_output(args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('/Users/marcos/temp/web-platform-tests/_venv/bin/pip', 'install', u'mozdownload')' returned non-zero exit status -6
```

**Comment by marcoscaceres** [comment]
Maybe related? https://github.com/web-platform-tests/wpt/issues/9007

**Comment by Hexcles** [comment]
Doesn't seem to be related to #9007 at the first glance.

What's your Python version? Are you using the stock macOS Python or something from Homebrew? Could you also `rm -r _venv` and try again?

**Comment by marcoscaceres** [comment]
Python 2.7.15

Using: 
/usr/local/bin/python

Deleted _venv, now get: 
```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 111, in main
    venv = setup_virtualenv(main_args.venv, props)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/wpt.py", line 84, in setup_virtualenv
    venv.start()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/virtualenv.py", line 46, in start
    self.create()
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/virtualenv.py", line 25, in create
    call(self.virtualenv, self.path, "-p", sys.executable)
  File "/Users/marcos/temp/web-platform-tests/tools/wpt/utils.py", line 44, in call
    return subprocess.check_output(args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Hexcles** [comment]
`/usr/local/Cellar`, so Homebrew it is.

Looks like you don't have `virtualenv` (and perhaps `pip` is also missing). They should be installed by Homebrew automatically. Perhaps try `brew update && brew reinstall python@2`.

**Comment by foolip** [comment]
If the problem is missing `virtualenv`, then https://github.com/web-platform-tests/wpt/issues/6565 is related, filed by none other than @marcoscaceres. Sounds like in addition to documenting it, we should make it fail in some much more obvious way. @Hexcles, do you have a good grasp on what needs to be done here, can I assign you?

**Comment by Hexcles** [comment]
First, @marcoscaceres can you confirm reinstalling `python@2` or explicitly installing `virtualenv` (using `pip`) solves the problem?

If so, let's close this issue and continue the discussion in #6565 .

**Comment by marcoscaceres** [comment]
Not much joy.... 

```Bash
╰─➤  python --version
Python 2.7.15
╰─➤  pip install pip
Requirement already satisfied: pip in /usr/local/lib/python2.7/site-packages (10.0.1)
```

**Comment by marcoscaceres** [comment]
So, Firefox is running now... but trying to run Chrome crashes python... but at least it's kinda working. So, closing for now. At least we have a potential fix (uninstall/reinstall virtualenv)

**Comment by Hexcles** [comment]
@marcoscaceres regarding the crash, you're probably running into #9007 which has a reportedly working solution.

**Comment by marcoscaceres** [comment]
Heh, indeed!! It's that one!
