### ISSUE TITLE
InsecureCertificateException error trying to run wpt

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#12370]
Getting the following, but I've disabled my firewall on MacOS:

> ./wpt run firefox payment-request/payment-request-canmakepayment-method.https.html

Any ideas?

```BASH
0:24.00 CRITICAL Loading initial page https://web-platform.test:8443/testharness_runner.html failed. Ensure that the there are no other programs bound to this port and that your firewall rules or network setup does not prevent access.\eTraceback (most recent call last):
  File "/Users/marcos/temp/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 125, in load_runner
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/Users/marcos/temp/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 168, in dismiss_alert
    f()
  File "/Users/marcos/temp/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 125, in <lambda>
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/Users/marcos/temp/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 1592, in navigate
    {"url": url})
  File "/Users/marcos/temp/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/Users/marcos/temp/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 741, in _send_message
    self._handle_error(err)
  File "/Users/marcos/temp/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 765, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
InsecureCertificateException:
stacktrace:
	WebDriverError@chrome://marionette/content/error.js:178:5
	InsecureCertificateError@chrome://marionette/content/error.js:297:5
	handleReadyState@chrome://marionette/content/listener.js:272:21
	handleEvent@chrome://marionette/content/listener.js:245:9
```

**Comment by sideshowbarker** [comment]
> …Ensure that the there are no other programs bound to this port…

You checked to make sure there’s nothing else listening on port 8443?

```
lsof -i:8443
```
or
```
lsof -nP -i4TCP:8443
```

**Comment by marcoscaceres** [comment]
Yep, checked. Nothing :(

**Comment by sideshowbarker** [comment]
OK I was able to reproduce this by uninstalling certutil so that wpt claims *“Can't find certutil, certificates will not be checked”*.

So now I get essentially the same stack trace as reported in the issue description—
```
 0:23.09 CRITICAL Loading initial page https://web-platform.test:8443/testharness_runner.html failed. Ensure that the there are no other programs bound to this port and that your firewall rules or network setup does not prevent access.\eTraceback (most recent call last):
  File "/Users/mike/workspace/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 125, in load_runner
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/Users/mike/workspace/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 168, in dismiss_alert
    f()
  File "/Users/mike/workspace/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 125, in <lambda>
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/Users/mike/workspace/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 1592, in navigate
    {"url": url})
  File "/Users/mike/workspace/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/Users/mike/workspace/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 741, in _send_message
    self._handle_error(err)
  File "/Users/mike/workspace/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 765, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
InsecureCertificateException:
stacktrace:
	WebDriverError@chrome://marionette/content/error.js:178:5
	InsecureCertificateError@chrome://marionette/content/error.js:297:5
	handleReadyState@chrome://marionette/content/listener.js:268:21
	handleEvent@chrome://marionette/content/listener.js:241:9
	EventListener.handleEvent*handleEvent@chrome://marionette/content/listener.js:229:9
	EventListener.handleEvent*start@chrome://marionette/content/listener.js:142:7
	navigate@chrome://marionette/content/listener.js:404:7
	get@chrome://marionette/content/listener.js:1039:5
	MessageListener.receiveMessage*startListeners@chrome://marionette/content/listener.js:539:3
	registerSelf@chrome://marionette/content/listener.js:458:5
	@chrome://marionette/content/listener.js:1679:1
```

**Comment by marcoscaceres** [comment]
Thanks for fixing this, btw. Confirming it's working now :)
