### ISSUE TITLE
Trying to run any WebDriver test fails in Edge

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12461]
Everything fails like:

```
ERROR /webdriver/tests/switch_to_window/switch.py - the environment variable is longer than 32767 bytes
Traceback (most recent call last):
  File "C:\Users\gsnedders\Documents\web-platform-tests\tools\wptrunner\wptrunner\executors\base.py", line 405, in _run
    self.result = True, self.func(self.session, self.path, self.timeout)
  File "C:\Users\gsnedders\Documents\web-platform-tests\tools\wptrunner\wptrunner\executors\base.py", line 371, in do_wd
spec
    timeout=timeout)
  File "C:\Users\gsnedders\Documents\web-platform-tests\tools\wptrunner\wptrunner\executors\pytestrunner\runner.py", lin
e 47, in run
    os.environ["WD_SERVER_CONFIG"] = json.dumps(server_config.as_dict())
  File "C:\Users\gsnedders\Documents\wpt-env\lib\os.py", line 422, in __setitem__
    putenv(key, item)
ValueError: the environment variable is longer than 32767 bytes
```

bisect points at ff4e72e977d0776510aea28ddfb497c7fc12e848 from #10953

**Comment by gsnedders** [comment]
cc/ @InstyleVII
