### ISSUE TITLE
Unable to update expectations 

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12696]
```
$ ./wpt run --metadata infrastructure/metadata/ --manifest MANIFEST.json --log-raw safari.log safari infrastructure/
$ ./wpt update-expectations --product safari --metadata infrastructure/metadata/ --manifest MANIFEST.json safari.log 
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/update.py", line 32, in update_expectations
    updater.run()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/update.py", line 150, in run
    rv = update_runner.run()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/base.py", line 61, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/base.py", line 32, in run
    self.create(state)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/update.py", line 96, in create
    runner.run()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/base.py", line 61, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/base.py", line 32, in run
    self.create(state)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wptrunner/wptrunner/update/metadata.py", line 14, in create
    state.property_order = property_order + state.extra_properties
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

Hacking that line to be `state.property_order = (property_order or []) + (state.extra_properties or [])` causes it to change the expectations of several tests unconditionally, instead of adding exceptions for safari, which is what I'd expect given I didn't pass in `--ignore-existing`.

**Comment by gsnedders** [comment]
(I have no idea whether the above is the correct fix because I don't understand the code at all.)

**Comment by foolip** [comment]
@jgraham, have you seen this error? I ran into the same thing, and used @gsnedders' workaround.

**Comment by mdittmer** [comment]
_friendly ping_. Glad to see this has a workaround, but should the issue be re-prioritized or receive an owner?

**Comment by gsnedders** [comment]
We should just land some workaround, at least, before de-prioritizing.
