### ISSUE TITLE
Make --headless the default for Chrome

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13195]
Support for `--headless` and `--no-headless` was added in https://github.com/web-platform-tests/wpt/issues/13005 / https://github.com/web-platform-tests/wpt/pull/13076. It's enabled by default for Firefox but not for Chrome.

For Chrome, some tests are failing with `--headless`. Fix those and flip the default.

**Comment by foolip** [comment]
@jgraham do you recall which the failing tests were? Some in infrastructure/ perhaps?

**Comment by Hexcles** [comment]
@jgraham what are the "smoke tests" broken by headless on Chrome?

**Comment by jgraham** [comment]
```
./wpt run --install-fonts --metadata infrastructure/metadata/ --log-tbpl=tbpl.log chrome infrastructure/

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 137 checks (46 tests, 91 subtests)
Expected results: 135
Skipped: 2 tests
OK
 1:37.99 INFO Closing logging queue
 1:37.99 INFO queue closed
```

```
./wpt run --headless --install-fonts --metadata infrastructure/metadata/ --log-tbpl=tbpl.log chrome infrastructure/

[…]

Unexpected Results
------------------
/infrastructure/assumptions/ahem.html
  FAIL /infrastructure/assumptions/ahem.html - /infrastructure/assumptions/ahem.html 1454a0ff3cf9136b81887525b2d5d79bfe299e80
/infrastructure/assumptions/ahem-ref.html 96ad8d6e22c85614f2bbade4d1732f628a98bc1d
Testing 1454a0ff3cf9136b81887525b2d5d79bfe299e80 == 96ad8d6e22c85614f2bbade4d1732f628a98bc1d
/infrastructure/reftest/reftest.https.html
  FAIL /infrastructure/reftest/reftest.https.html - /infrastructure/reftest/reftest.https.html 431b3dc7dbfb26ba548c39598135074daded1bb7
/infrastructure/reftest/green.html 3d4f198a06ccb2ed8cf21ed8029d3a9d230d02be
Testing 431b3dc7dbfb26ba548c39598135074daded1bb7 == 3d4f198a06ccb2ed8cf21ed8029d3a9d230d02be
/infrastructure/server/context.any.serviceworker.html
  TIMEOUT /infrastructure/server/context.any.serviceworker.html
/infrastructure/server/secure-context.https.any.html
  TIMEOUT /infrastructure/server/secure-context.https.any.html
/infrastructure/server/secure-context.https.any.serviceworker.html
  TIMEOUT /infrastructure/server/secure-context.https.any.serviceworker.html
/infrastructure/server/secure-context.https.any.sharedworker.html
  TIMEOUT /infrastructure/server/secure-context.https.any.sharedworker.html
/infrastructure/server/secure-context.https.any.worker.html
  TIMEOUT /infrastructure/server/secure-context.https.any.worker.html
/infrastructure/server/wpt-server-http.sub.html
  FAIL HTTPS protocol, no subdomain - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:141:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
  FAIL HTTPS protocol, www subdomain #1 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:149:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
  FAIL HTTPS protocol, www subdomain #2 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:157:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
  FAIL HTTPS protocol, www subdomain #3 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:165:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
  FAIL HTTPS protocol, punycode subdomain #1 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:173:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
  FAIL HTTPS protocol, punycode subdomain #2 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:181:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at HTMLImageElement.img.onerror (http://web-platform.test:8000/infrastructure/server/wpt-server-http.sub.html:18:5)
/infrastructure/server/wpt-server-websocket.sub.html
  FAIL WSS protocol, no subdomain - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:75:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
  FAIL WSS protocol, www subdomain #1 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:83:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
  FAIL WSS protocol, www subdomain #2 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:91:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
  FAIL WSS protocol, www subdomain #3 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:99:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
  FAIL WSS protocol, punycode subdomain #1 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:107:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
  FAIL WSS protocol, punycode subdomain #2 - assert_true: expected true got false
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:115:5)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1561:25)
    at http://web-platform.test:8000/resources/testharness.js:1585:35
    at WebSocket.<anonymous> (http://web-platform.test:8000/infrastructure/server/wpt-server-websocket.sub.html:17:5)
```
