### ISSUE TITLE
TestRunnerManager AssertionError assert isinstance(self.state, RunnerManagerState.restarting)

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#13276]
[wpt-chrome-dev-testharness-6](https://tools.taskcluster.net/groups/HuC12DhIShShqh7UcovreA/tasks/Pn2YWHFYRuWDpl3y1bWEAA/runs/0/logs/public%2Flogs%2Flive.log) ends with:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 359, in run
    new_state = self.wait_event()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 434, in wait_event
    return f(*data)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 653, in error
    self.restart_runner()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 644, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError
```

This is just after we've had the browser fail to respond on several occasions. This looks like we aren't cleaning up properly when exiting abnormally.

**Comment by foolip** [comment]
Per @gsnedders this was the cause behind https://github.com/web-platform-tests/wpt/pull/17219#issuecomment-501272482 so perhaps this issue is more important than we thought :)

@LukeZielinski it seems that a lot of issues around TestRunnerManager might be incidentally fixed by refactoring the executor to live in another process and communicate over some protocol. Would you guess this is one of them?

**Comment by LukeZielinski** [comment]
Yeah, seems likely that this would have to be rewritten if those were split into different processes. But we'd likely need to handle such a scenario (abnormal exit + cleanup) in the split world too.

**Comment by foolip** [comment]
Changing to roadmap since @gsnedders says this a bug in the handling of the state machine, fix not obvious but it's affecting runs. @jgraham might have ideas.

Not assigning to anybody though, yet.

**Comment by gsnedders** [comment]
Fundamentally, `TestRunnerManager.error` will always throw because it calls `restart_runner` which asserts we're in the restart state. I'm not entirely sure if the right fix is just:

```
diff --git a/tools/wptrunner/wptrunner/testrunner.py b/tools/wptrunner/wptrunner/testrunner.py
index 44b5401e4f..ddce7f47f3 100644
--- a/tools/wptrunner/wptrunner/testrunner.py
+++ b/tools/wptrunner/wptrunner/testrunner.py
@@ -660,7 +660,7 @@ class TestRunnerManager(threading.Thread):
 
     def error(self, message):
         self.logger.error(message)
-        self.restart_runner()
+        return RunnerManagerState.restarting(0)
 
     def stop_runner(self, force=False):
         """Stop the TestRunner and the browser binary."""
```

And testing this isn't that easy.
