### ISSUE TITLE
resources/tests CI job is intermittently failing

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#13568]
https://github.com/web-platform-tests/wpt/pull/13567, https://github.com/web-platform-tests/wpt/pull/13551, https://github.com/web-platform-tests/wpt/pull/13562, and https://github.com/web-platform-tests/wpt/pull/13561 are showing the following unrelated failure:
```
py27 runtests: commands[0] | pytest --binary=/home/travis/browsers/nightly/firefox/firefox -vv tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-3.9.1, py-1.7.0, pluggy-0.8.0 -- /home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/web-platform-tests/wpt/resources/test, inifile:
collecting 64 items                                                            INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 181, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 220, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 230, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 435, in perform_collect
INTERNALERROR>     items = self._perform_collect(args, genitems)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 474, in _perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 660, in genitems
INTERNALERROR>     node.ihook.pytest_itemcollected(item=node)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/nodes.py", line 116, in ihook
INTERNALERROR>     return self.session.gethookproxy(self.fspath)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 422, in gethookproxy
INTERNALERROR>     my_conftestmodules = pm._getconftestmodules(fspath)
INTERNALERROR>   File "/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/lib/python2.7/site-packages/_pytest/config/__init__.py", line 383, in _getconftestmodules
INTERNALERROR>     if path.isfile():
INTERNALERROR> AttributeError: 'str' object has no attribute 'isfile'
========================= no tests ran in 0.76 seconds =========================
ERROR: InvocationError for command '/home/travis/build/web-platform-tests/wpt/resources/test/.tox/py27/bin/pytest --binary=/home/travis/browsers/nightly/firefox/firefox -vv tests' (exited with code 3)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

This is preventing merging PRs.

**Comment by jdm** [comment]
Oh, I just saw https://github.com/web-platform-tests/wpt/pull/13565.
