### ISSUE TITLE
`./wpt run` can exit successfully even when "Max restarts exceeded"

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13747]
This happened in https://github.com/foolip/wpt/runs/26798499. The [log](https://gist.github.com/foolip/f47d07edbac85e63fcc8010a6033951b) ends like this:
```
2018-10-27T11:27:36.2295210Z WebDriver was not accessible within the timeout:
2018-10-27T11:27:36.2295570Z Traceback (most recent call last):
2018-10-27T11:27:36.2295780Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/webdriver_server.py", line 73, in _run
2018-10-27T11:27:36.2295940Z     wait_for_service((self.host, self.port))
2018-10-27T11:27:36.2296130Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/webdriver_server.py", line 265, in wait_for_service
2018-10-27T11:27:36.2296270Z     raise socket.error("Service is unavailable: %s:%i" % addr)
2018-10-27T11:27:36.2296390Z error: Service is unavailable: 127.0.0.1:4445
2018-10-27T11:27:36.2296460Z 
2018-10-27T11:27:36.2298670Z Traceback (most recent call last):
2018-10-27T11:27:36.2299010Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 199, in init
2018-10-27T11:27:36.2299310Z     self.browser.start(group_metadata=group_metadata, **self.browser_settings)
2018-10-27T11:27:36.2299550Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/browsers/safari.py", line 66, in start
2018-10-27T11:27:36.2299690Z     self.server.start(block=False)
2018-10-27T11:27:36.2299810Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/webdriver_server.py", line 49, in start
2018-10-27T11:27:36.2300020Z     self._run(block)
2018-10-27T11:27:36.2300140Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/webdriver_server.py", line 73, in _run
2018-10-27T11:27:36.2300320Z     wait_for_service((self.host, self.port))
2018-10-27T11:27:36.2300450Z   File "/Users/vsts/agent/2.141.1/work/1/s/tools/wptrunner/wptrunner/webdriver_server.py", line 265, in wait_for_service
2018-10-27T11:27:36.2301070Z     raise socket.error("Service is unavailable: %s:%i" % addr)
2018-10-27T11:27:36.2301190Z error: Service is unavailable: 127.0.0.1:4445
2018-10-27T11:27:36.2301260Z 
2018-10-27T11:27:36.2301340Z Max restarts exceeded
2018-10-27T11:27:36.2309310Z 
2018-10-27T11:27:36.2309910Z Ran 1 tests finished in 276.0 seconds.
2018-10-27T11:27:36.2311190Z   • 1 ran as expected. 1 tests skipped.
```

And yet the exit code was 0. It looks like this is because this failure mode caused wptrunner to not know what the total number of tests should be.

The failure point:
https://github.com/web-platform-tests/wpt/blob/f6bca7b6218f591edc1bcb87c9ab0837ca41970b/tools/wptrunner/wptrunner/testrunner.py#L456

**Comment by gsnedders** [comment]
This is what prompted #13073 too. Basically a dupe.

**Comment by foolip** [comment]
Alright, treating as dupe.
