### ISSUE TITLE
wpt run command line could be too long in tools/ci/taskcluster-run.py

### ISSUE THREAD

**Issue by qiuzhong** [web-platform-tests/wpt#14186]
tools/ci/taskcluster-run.py could be used for running the affected tests between commits only. It gets the affected test list and converts it to a string:

https://github.com/web-platform-tests/wpt/blob/579140910974daa5394f741197b0b68179882490/tools/ci/taskcluster-run.py#L16

and passes the string to wpt command line:

https://github.com/web-platform-tests/wpt/blob/579140910974daa5394f741197b0b68179882490/tools/ci/taskcluster-run.py#L82

The problem is when the test list is large, this command line could be very long,  like this:

```
python ./wpt run --log-tbpl-level=info --log-tbpl=- -y --no-pause --no-restart-on-unexpected --install-fonts --no-headless chrome html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_2.html html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_3.html html/browsers/browsing-the-web/navigating-across-documents/010.html html/browsers/browsing-the-web/navigating-across-documents/012.html html/browsers/browsing-the-web/navigating-across-documents/013.html html/browsers/browsing-the-web/navigating-across-documents/014.html html/browsers/browsing-the-web/navigating-across-documents/015.html html/browsers/history/the-history-interface/history_back_1.html html/browsers/history/the-history-interface/history_forward_1.html html/browsers/history/the-history-interface/history_go_no_argument.html html/browsers/history/the-history-interface/history_go_to_uri.html html/browsers/history/the-history-interface/history_go_undefined.html html/browsers/history/the-history-interface/history_go_zero.html html/browsers/history/the-history-interface/traverse_the_history_3.html html/browsers/history/the-history-interface/traverse_the_history_4.html html/browsers/history/the-history-interface/traverse_the_history_5.html html/browsers/history/the-history-interface/traverse_the_history_unload_1.html html/browsers/history/the-location-interface/scripted_click_assign_during_load.html html/browsers/history/the-location-interface/scripted_form_submit_assign_during_load.html html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/close_script_defer.html html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_3.html html/semantics/scripting-1/the-script-element/execution-timing/078.html html/semantics/scripting-1/the-script-element/execution-timing/081.html html/semantics/scripting-1/the-script-element/execution-timing/082.html html/semantics/scripting-1/the-script-element/execution-timing/091.html html/semantics/scripting-1/the-script-element/execution-timing/092.html html/semantics/scripting-1/the-script-element/execution-timing/094.html html/semantics/scripting-1/the-script-element/execution-timing/095.html html/semantics/scripting-1/the-script-element/execution-timing/097.html html/semantics/scripting-1/the-script-element/execution-timing/122.html html/semantics/scripting-1/the-script-element/execution-timing/123.html html/semantics/scripting-1/the-script-element/execution-timing/125.html html/semantics/scripting-1/the-script-element/execution-timing/126.html html/semantics/scripting-1/the-script-element/execution-timing/136.html html/semantics/scripting-1/the-script-element/execution-timing/137.html html/semantics/scripting-1/the-script-element/execution-timing/138.html html/semantics/scripting-1/the-script-element/execution-timing/139.html html/semantics/scripting-1/the-script-element/execution-timing/140.html html/semantics/scripting-1/the-script-element/execution-timing/141.html html/semantics/scripting-1/the-script-element/execution-timing/142.html html/semantics/scripting-1/the-script-element/execution-timing/143.html html/semantics/scripting-1/the-script-element/execution-timing/144.html html/semantics/scripting-1/the-script-element/execution-timing/145.html
```

In some extreme cases, the test list is too long and may exceeds the python [command line length limit on Windows](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation)

**Comment by foolip** [comment]
@gsnedders funny that you should mention this possibility yesterday, and then it immediately happened :)

In https://github.com/web-platform-tests/wpt/pull/14156 I'm working on `./wpt run --affected` which I'll probably break out into its own PR. I think Taskcluster could then use the same setup.

cc @jugglinmike who wrote taskcluster-run.py.

**Comment by foolip** [comment]
It never would be, but we also can't use the same approach on Windows when we get to that.

@qiuzhong did you run into this on one of your PRs touching many files?

**Comment by qiuzhong** [comment]
@foolip, yes. 

I failed to run `tools/ci/taskcluster-run.py` on Windows as it always said `Quitting because no tests were affected` even there're obviously between two commits.

I did run `python tools/ci/taskcluster-run.py --commit-range HEAD~ chrome` to check results on Linux after I committed. But I almost got this error like this every time:
```
Traceback (most recent call last):
  File "tools/ci/taskcluster-run.py", line 103, in <module>
    main(**vars(parser.parse_args()))
  File "tools/ci/taskcluster-run.py", line 86, in main
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', './wpt', 'run', '--log-tbpl-level=info', '--log-tbpl=-', '-y', '--no-pause', '--no-restart-on-unexpected', '--install-fonts', '--no-headless', 'chrome', 'html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_2.html', 'html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_3.html', 'html/browsers/browsing-the-web/navigating-across-documents/010.html', 'html/browsers/browsing-the-web/navigating-across-documents/012.html', 'html/browsers/browsing-the-web/navigating-across-documents/013.html', 'html/browsers/browsing-the-web/navigating-across-documents/014.html', 'html/browsers/browsing-the-web/navigating-across-documents/015.html', 'html/browsers/browsing-the-web/navigating-across-documents/javascript-url-query-fragment-components.html', 'html/browsers/history/the-history-interface/history_back_1.html', 'html/browsers/history/the-history-interface/history_forward_1.html', 'html/browsers/history/the-history-interface/history_go_no_argument.html', 'html/browsers/history/the-history-interface/history_go_to_uri.html', 'html/browsers/history/the-history-interface/history_go_undefined.html', 'html/browsers/history/the-history-interface/history_go_zero.html', 'html/browsers/history/the-history-interface/traverse_the_history_3.html', 'html/browsers/history/the-history-interface/traverse_the_history_4.html', 'html/browsers/history/the-history-interface/traverse_the_history_5.html', 'html/browsers/history/the-history-interface/traverse_the_history_unload_1.html', 'html/browsers/history/the-location-interface/scripted_click_assign_during_load.html', 'html/browsers/history/the-location-interface/scripted_form_submit_assign_during_load.html', 'html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/close_script_defer.html', 'html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_3.html', 'html/interaction/focus/focus-01.html', 'html/interaction/focus/sequential-focus-navigation-and-the-tabindex-attribute/focus-tabindex-order.html', 'html/semantics/embedded-content/media-elements/event_canplay.html', 'html/semantics/embedded-content/media-elements/event_canplay_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_canplaythrough.html', 'html/semantics/embedded-content/media-elements/event_canplaythrough_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_loadeddata.html', 'html/semantics/embedded-content/media-elements/event_loadeddata_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_loadedmetadata.html', 'html/semantics/embedded-content/media-elements/event_loadedmetadata_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_loadstart.html', 'html/semantics/embedded-content/media-elements/event_loadstart_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_order_canplay_canplaythrough.html', 'html/semantics/embedded-content/media-elements/event_order_canplay_playing.html', 'html/semantics/embedded-content/media-elements/event_order_loadedmetadata_loadeddata.html', 'html/semantics/embedded-content/media-elements/event_order_loadstart_progress.html', 'html/semantics/embedded-content/media-elements/event_pause.html', 'html/semantics/embedded-content/media-elements/event_pause_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_play.html', 'html/semantics/embedded-content/media-elements/event_play_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_playing.html', 'html/semantics/embedded-content/media-elements/event_playing_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_progress.html', 'html/semantics/embedded-content/media-elements/event_progress_noautoplay.html', 'html/semantics/embedded-content/media-elements/event_timeupdate.html', 'html/semantics/embedded-content/media-elements/event_timeupdate_noautoplay.html', 'html/semantics/embedded-content/media-elements/interfaces/TextTrack/activeCues.html', 'html/semantics/embedded-content/media-elements/interfaces/TextTrack/addCue.html', 'html/semantics/embedded-content/media-elements/interfaces/TextTrack/removeCue.html', 'html/semantics/embedded-content/media-elements/networkState_during_loadstart.html', 'html/semantics/embedded-content/media-elements/networkState_during_progress.html', 'html/semantics/embedded-content/media-elements/paused_false_during_play.html', 'html/semantics/embedded-content/media-elements/paused_true_during_pause.html', 'html/semantics/embedded-content/media-elements/readyState_during_canplay.html', 'html/semantics/embedded-content/media-elements/readyState_during_canplaythrough.html', 'html/semantics/embedded-content/media-elements/readyState_during_loadeddata.html', 'html/semantics/embedded-content/media-elements/readyState_during_loadedmetadata.html', 'html/semantics/embedded-content/media-elements/readyState_during_playing.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/003.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/004.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/005.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/006.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/007.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/008.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/009.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/010.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/011.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/012.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/013.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/014.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/015.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/016.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/017.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/018.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/019.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/020.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/021.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/022.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/023.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/024.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/025.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/026.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/027.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/028.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/029.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/030.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/031.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/032.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/033.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/034.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/035.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/036.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/037.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/038.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/039.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/040.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/041.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/042.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/043.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/044.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/045.html', 'html/semantics/embedded-content/media-elements/track/track-element/cors/046.html', 'html/semantics/scripting-1/the-script-element/execution-timing/078.html', 'html/semantics/scripting-1/the-script-element/execution-timing/081.html', 'html/semantics/scripting-1/the-script-element/execution-timing/082.html', 'html/semantics/scripting-1/the-script-element/execution-timing/091.html', 'html/semantics/scripting-1/the-script-element/execution-timing/092.html', 'html/semantics/scripting-1/the-script-element/execution-timing/094.html', 'html/semantics/scripting-1/the-script-element/execution-timing/095.html', 'html/semantics/scripting-1/the-script-element/execution-timing/097.html', 'html/semantics/scripting-1/the-script-element/execution-timing/122.html', 'html/semantics/scripting-1/the-script-element/execution-timing/123.html', 'html/semantics/scripting-1/the-script-element/execution-timing/125.html', 'html/semantics/scripting-1/the-script-element/execution-timing/126.html', 'html/semantics/scripting-1/the-script-element/execution-timing/136.html', 'html/semantics/scripting-1/the-script-element/execution-timing/137.html', 'html/semantics/scripting-1/the-script-element/execution-timing/138.html', 'html/semantics/scripting-1/the-script-element/execution-timing/139.html', 'html/semantics/scripting-1/the-script-element/execution-timing/140.html', 'html/semantics/scripting-1/the-script-element/execution-timing/141.html', 'html/semantics/scripting-1/the-script-element/execution-timing/142.html', 'html/semantics/scripting-1/the-script-element/execution-timing/143.html', 'html/semantics/scripting-1/the-script-element/execution-timing/144.html', 'html/semantics/scripting-1/the-script-element/execution-timing/145.html']' returned non-zero exit status 1
```

I feel like the command line is too long when this script calls `wpt run <tests>`. But I don't think it's the cause of this error on Linux. Then I checked the command line length limits: it's 2097152 bytes for [Linux](https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit?answertab=active#tab-top) and 8191 characters for [Windows](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation).

**Comment by foolip** [comment]
Ah, I guess you were trying to reproduce the problem from Taskcluster on Windows? That it doesn't work is probably no suprise to @jgraham or @jugglinmike,  but I wonder if the Taskcluster logs could give instructions for how to reproduce locally, including the required Docker bits?

**Comment by qiuzhong** [comment]
I didn't run the script from Taskcluster CI on Windows. I simply ran it locally.

**Comment by Hexcles** [comment]
This should no longer be an issue with #14354 (we no longer pass the list of tests via CLI args).
