### ISSUE TITLE
Taskcluster failured due to memory "Cannot allocate memory"

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14207]
The [7 most recent commits to master](https://github.com/web-platform-tests/wpt/commits/bf2bef64b0056d8641ba1caf65315fa28221add9) at the time of writing all have failed Taskcluster runs:
https://tools.taskcluster.net/groups/f9h2rnpNSGSZtf8XqKsI7g
https://tools.taskcluster.net/groups/PEZ79dY9R2GhxheZKTXC3Q
https://tools.taskcluster.net/groups/MEBnx5kARYKxgH42Ot3zsQ
https://tools.taskcluster.net/groups/HiCTerPsTsGZXTaF_Gz4qQ
https://tools.taskcluster.net/groups/Ekt9SdPFT2umvUiNaiTaWQ (for master)
https://tools.taskcluster.net/groups/DWgMz-OFQOKp5iktSe1gSg (for epochs/daily)
https://tools.taskcluster.net/groups/BotCYMVpT--o_Kz1D99puQ
https://tools.taskcluster.net/groups/DevtLTz6TGeBFy8QOFQh8A

All of them have some task that has failed with "Cannot allocate memory" in the log.
<details>
<summary>Example from the first above:</summary>

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/test/web-platform-tests/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 540, in run
    rv = run_single(venv, **kwargs) > 0
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 547, in run_single
    return wptrunner.start(**kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 331, in start
    return not run_tests(**kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py", line 188, in run_tests
    env_extras) as test_environment:
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/environment.py", line 61, in __init__
    self.cache_manager = multiprocessing.Manager()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 524, in start
    self._process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "./tools/ci/taskcluster-run.py", line 103, in <module>
    main(**vars(parser.parse_args()))
  File "./tools/ci/taskcluster-run.py", line 86, in main
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', './wpt', 'run', '--channel=nightly', '--log-wptreport=../artifacts/wpt_report.json', '--no-fail-on-unexpected', '--test-type=testharness', '--this-chunk=14', '--total-chunks=15', '--log-tbpl-level=info', '--log-tbpl=-', '-y', '--no-pause', '--no-restart-on-unexpected', '--install-fonts', '--no-headless', '--install-browser', 'firefox']' returned non-zero exit status 1
```
</details>

**Comment by foolip** [comment]
It started happening when https://github.com/web-platform-tests/wpt/pull/14025 was merged. That seems like a somewhat unlikely cause, but I'll try reverting it anyway to see.

**Comment by foolip** [comment]
Ah... We don't even fetch the tags in the Taskcluster setup:
https://github.com/web-platform-tests/wpt/blob/1ede22e333195e47e13260a58ce89ef3220c19c7/tools/docker/start.sh#L27-L36

**Comment by foolip** [comment]
All right, it was my fault, Taskcluster is now passing again.
