### ISSUE TITLE
Firefox stability jobs failing when running reftests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#15596]
appears to be regression from https://github.com/web-platform-tests/wpt/pull/15488 (cc @jugglinmike); @jgraham suspects Marionette's `reftest:teardown` doesn't actually work.

**Comment by gsnedders** [comment]
For those wondering if a Firefox stability job is affected by this, you'll have "MISSING: 9/10", and a sequence of tracebacks at the end of the log like:

```
TEST-START | /css/vendor-imports/mozilla/mozilla-central-reftests/shapes1/float-retry-push-circle.html
Run 1/10
PID 272 | 1551290483441	Marionette	INFO	No differences allowed
Error running command reset with arguments ():
Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 100, in run
    rv = commands[command](*args)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 113, in reset
    self.executor.reset()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 784, in reset
    self.implementation.reset(**self.implementation_kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 869, in reset
    self.setup(screenshot)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 865, in setup
    self.executor.protocol.marionette._send_message("reftest:setup", data)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 741, in _send_message
    self._handle_error(err)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 765, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
NoSuchWindowException: Browsing context has been discarded
stacktrace:
	WebDriverError@chrome://marionette/content/error.js:179:5
	NoSuchWindowError@chrome://marionette/content/error.js:411:5
	assert.that/<@chrome://marionette/content/assert.js:417:13
	assert.open@chrome://marionette/content/assert.js:175:25
	setup@chrome://marionette/content/reftest.js:74:33
	GeckoDriver.prototype.setupReftest@chrome://marionette/content/driver.js:3529:17
	Async*despatch@chrome://marionette/content/server.js:289:40
	async*execute@chrome://marionette/content/server.js:262:16
	async*onPacket/<@chrome://marionette/content/server.js:235:20
	async*onPacket@chrome://marionette/content/server.js:236:9
	_onJSONObjectReady/<@chrome://marionette/content/transport.js:492:20


Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 373, in run
    new_state = self.wait_event()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 448, in wait_event
    return f(*data)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 665, in error
    self.restart_runner()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 656, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError

Browser exited with return code -15
PROCESS LEAKS None
Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 167, in run_test
    result = self.do_test(test)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 808, in do_test
    result = self.implementation.run_test(test)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 880, in run_test
    "height": 600})["value"]
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/decorators.py", line 31, in _
    m._handle_socket_failure()
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 797, in _handle_socket_failure
    reraise(exc, val, tb)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/marionette.py", line 733, in _send_message
    msg = self.client.request(name, params)
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/transport.py", line 273, in request
    return self.receive()
  File "/home/test/web-platform-tests/_venv/lib/python2.7/site-packages/marionette_driver/transport.py", line 153, in receive
    chunk = self._sock.recv(bytes_to_recv)
error: [Errno 104] Connection reset by peer

Command left in command_queue during cleanup: 'test_ended', (<wptrunner.wpttest.ReftestTest /css/vendor-imports/mozilla/mozilla-central-reftests/shapes1/float-retry-push-circle.html>, (<wptrunner.wpttest.ReftestResult INTERNAL-ERROR>, []))
Closing logging queue
queue closed
PROCESS LEAKS None
Running wdspec tests
STDERR: Exception in thread TestRunnerManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 373, in run
    new_state = self.wait_event()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 448, in wait_event
    return f(*data)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 665, in error
    self.restart_runner()
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 656, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError
No wdspec tests to run
Running testharness tests
No testharness tests to run
Got 0 unexpected results
SUITE-END | took 5s
```

**Comment by gsnedders** [comment]
A lot of jobs seem to be showing PASS/FAIL flakiness now? That's… even worse, given it's not at all obvious what's causing it. :/

**Comment by gsnedders** [comment]
OK, so the status here is of the seven previous failures https://github.com/web-platform-tests/wpt/pull/15581 and https://github.com/web-platform-tests/wpt/pull/15591 have failed again. The former is weird (the rightmost 200px of the ref screenshot when failing are translucent white?!), the latter I suspect might be a genuine Firefox bug?

**Comment by dholbert** [comment]
> The former is weird (the rightmost 200px of the ref screenshot when failing are translucent white?!) 

We ran into something similar in https://github.com/web-platform-tests/wpt/pull/15534#issuecomment-467659525 2 days ago, too, for what it's worth.

**Comment by gsnedders** [comment]
@dholbert well the former seems to have been fixed by the revert, so I guess this works again…
