### ISSUE TITLE
Unable to run reftests in stable release of Safari

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#15625]
[A recent change to the WebDriver reftest runner](https://github.com/web-platform-tests/wpt/pull/15222) introduced an invocation of the "set window rect" method with arguments "x" and "y" both set to the integer value `0`.

This command is rejected by the WebDriver implementation for the stable release of Safari ("safaridriver"), so all reftests are now failing for that browser. Here's an example of the error from [a recent test on wpt.fyi](https://wpt.fyi/results/infrastructure/reftest-wait.html?sha=44e2efb923):

    ERROR message: Parameter 'x' has a boolean value, which is not allowed.
    Traceback (most recent call last):
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/base.py", line 167, in run_test result = self.do_test(test)
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 419, in do_test self.protocol.webdriver.window.position = (0, 0)
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 20, in inner return func(self, *args, **kwargs)
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 274, in position self.session.send_session_command("POST", "window/rect", body)
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 508, in send_session_command return self.send_command(method, url, body)
      File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 472, in send_command raise err InvalidArgumentException: invalid argument (400): Parameter 'x' has a boolean value, which is not allowed.

Firefox, Chrome, and Safari Technology Preview all pass that test.

My initial guess is that this is the result of erroneous type coercion in safaridriver, though it seems unlikely that we're the first to try to move a Safari window to (0, 0).

@burg do you have any ideas about this?

**Comment by gsnedders** [comment]
INTERESTING.

Safari stable doesn't seem to accept 0 or 1 as a value here, though STP works fine, so I presume it's therefore fixed. (Sidenote: we don't seem to have boundary condition tests in the `webdriver` suite for this.) Ergh.

**Comment by burg** [comment]
It is indeed fixed and on its way to stable builds. This caused a lot of fallout for most client libraries. Alas, there was no WPT test for those inputs. Sorry!
