### ISSUE TITLE
wpt run fails without requests installed globally

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#15975]
```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 116, in main
    script, parser = import_command(prog, command, props)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 69, in import_command
    mod = __import__(mod_name)
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/run.py", line 11, in <module>
    from . import browser, install, testfiles, utils, virtualenv
  File "/Users/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/browser.py", line 13, in <module>
    import requests
ImportError: No module named requests
```

**Comment by gsnedders** [comment]
Hmm, maybe just something odd going on with PyPy?

**Comment by gsnedders** [comment]
Oh, no, it's virtualenv's `activate_this.py` not supporting PyPy till recently.
