### ISSUE TITLE
`wpt manifest` requires git even when `--work` is used

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#16245]
I've only observed the problem in the following setup: in a test root that is not a git repo and does not have an existing `MANIFEST.json`, running `wpt manifest --work --test-root` would produce the following error:

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/usr/local/google/home/robertma/github/wpt/tools/wpt/wpt.py", line 136, in main
    rv = script(*args, **kwargs)
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/update.py", line 90, in run
    update_from_cli(**kwargs)
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/update.py", line 37, in update_from_cli
    download_from_github(path, tests_root)
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/download.py", line 131, in download_from_github
    force=force)
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/download.py", line 80, in download_manifest
    tags = tags_func()
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/download.py", line 130, in <lambda>
    return download_manifest(path, lambda: merge_pr_tags(tests_root), github_url,
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/download.py", line 39, in merge_pr_tags
    for line in git("log", "--format=%D", "--max-count=%s" % max_count).split("\n"):
  File "/usr/local/google/home/robertma/github/wpt/tools/manifest/vcs.py", line 50, in git
    return subprocess.check_output(full_cmd, cwd=repo_path, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'log', '--format=%D', '--max-count=50']' returned non-zero exit status 128
```

Adding `--no-download` or `--rebuild` would work around the problem.

**Comment by Hexcles** [comment]
cc @gsnedders

**Comment by gsnedders** [comment]
I think this was essentially fixed by `--work` being dropped? (Reopen if I'm wrong!)
