### ISSUE TITLE
--install-browser firefox doesn't work on Windows

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#17074]
Currently, we assume that `mozinstall` puts the binary directly within the destination folder; however, it is written to a subdirectory returned by `mozinstall.install` (as documented), and this causes `test_install_firefox` to fail.

Additionally, if you try to run tests with `--install-browser`, we seem to end up calling the system certutil.exe:

```
 1:54.64 DEBUG new state: initializing_browser
 1:54.64 DEBUG Dispatch init
 1:54.64 DEBUG Init called, starting browser and runner
 1:54.64 DEBUG Starting browser with settings {'lsan_allowed': set([]), 'mozleak_thresholds': False, 'lsan_max_stack_depth': None, 'check_leaks': False, 'mozleak_allowed': False}
 1:54.75 INFO Setting up ssl
 1:54.93 WARNING Failure during init Traceback (most recent call last):
  File "C:\Users\gsnedders\Documents\web-platform-tests\wpt\tools\wptrunner\wptrunner\testrunner.py", line 207, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\gsnedders\Documents\web-platform-tests\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 307, in start
    self.setup_ssl()
  File "C:\Users\gsnedders\Documents\web-platform-tests\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 485, in setup_ssl
    certutil("-N", "-d", cert_db_path, "-f", pw_path)
  File "C:\Users\gsnedders\Documents\web-platform-tests\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 474, in certutil
    stderr=subprocess.STDOUT),
  File "c:\python27\Lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['C:\\WINDOWS\\system32\\certutil.exe', '-N', '-d', 'c:\\users\\gsnedders\\appdata\\local\\temp\\tmpjdnvfq.mozrunner', '-f', 'c:\\users\\gsnedders\\appdata\\local\\temp\\tmpjdnvfq.mozrunner\\.crtdbpw']' returned non-zero exit status 1
```

**Comment by gsnedders** [comment]
OK, so the `certutil.exe` issue is solely #17075.

It might actually be only the `test_install_firefox` itself that's broken?
