### ISSUE TITLE
Dependency on requests?

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#17238]
This looks questionable:

```
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/mnt/home-extra/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 144, in main
    script, parser = import_command(prog, command, props)
  File "/mnt/home-extra/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/wpt.py", line 69, in import_command
    mod = __import__(mod_name)
  File "/mnt/home-extra/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/run.py", line 11, in <module>
    from . import browser, install, testfiles, utils, virtualenv
  File "/mnt/home-extra/gsnedders/Documents/other-projects/wpt/web-platform-tests/tools/wpt/browser.py", line 13, in <module>
    import requests
ImportError: No module named requests
```

**Comment by gsnedders** [comment]
Or maybe something else is broken with our virtualenv stuff with PyPy?

**Comment by foolip** [comment]
@gsnedders the dependency is in tools/wpt/requirements.txt, renamed in c6f022f773255fc5f723bf1c3236dedc7a6d8e8e and originally added in eb03407caedc4847867be415db35e1bba5bdb74b.

It's also in tools/wptrunner/requirements.txt, added in 6c2ffe0cb9b5cb1a31bd362ad10ae9c3b6873869.

Since the issue ended in a question mark I'm closing :)
