### ISSUE TITLE
lone surrogates in assertion message cause WebDriver to break running testharness.js tests

### ISSUE THREAD

**Issue by tabatkins** [web-platform-tests/wpt#17577]
For <https://wpt.fyi/results/css/css-syntax/input-preprocessing.html?label=master&label=experimental>, only Firefox successfully runs the tests. Safari errors out with a harness error, Chrome crashes before it even gets that far, and Edge is just... missing.

This test loads up just fine if I look at it manually in Chrome, so I'm not sure why the automated results are unhappy. Something weird about encodings?

**Comment by gsnedders** [comment]
This is a bug in Chrome or ChromeDriver.

Output from ChromeDriver:

```
 0:05.50 pid:83549 [1571128419.991][SEVERE]: Bad inspector message: {"id":16,"result":{"result":{"type":"object","value":{"status":0,"value":{"status":0,"value":["/css/css-syntax/input-preprocessing.html","complete",[0,null,null,[["\"foo\u0000\" becomes \"foo\ufffd\"",0,null,null],["\"f\u0000oo\" becomes \"f\ufffdoo\"",0,null,null],["\"\u0000foo\" becomes \"\ufffdfoo\"",0,null,null],["\"\u0000\" becomes \"\ufffd\"",0,null,null],["\"\u0000\u0000\u0000\" becomes \"\ufffd\ufffd\ufffd\"",0,null,null],["\"fooU+d800\" becomes \"foo\ufffd\"",1,"assert_equals: expected \"foo\\ufffd\" but got \"foo\ud800\"","    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:40:1"],["\"fU+d800oo\" becomes \"f\ufffdoo\"",1,"assert_equals: expected \"f\\ufffdoo\" but got \"f\ud800oo\"","    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:41:1"],["\"U+d800foo\" becomes \"\ufffdfoo\"",1,"assert_equals: expected \"\\ufffdfoo\" but got \"\ud800foo\"","    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:42:1"],["\"U+d800\" becomes \"\ufffd\"",1,"assert_equals: expected \"\\ufffd\" but got \"\ud800\"","    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:43:1"],["\"U+d800U+d800U+d800\" becomes \"\ufffd\ufffd\ufffd\"",1,"assert_equals: expected \"\\ufffd\\ufffd\\ufffd\" but got \"\ud800\ud800\ud800\"","    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:44:1"]]]]}}}}}
```

That JSON message:

```
{
  "id": 16,
  "result": {
    "result": {
      "type": "object",
      "value": {
        "status": 0,
        "value": {
          "status": 0,
          "value": [
            "/css/css-syntax/input-preprocessing.html",
            "complete",
            [
              0,
              null,
              null,
              [
                [
                  "\"foo\u0000\" becomes \"foo\ufffd\"",
                  0,
                  null,
                  null
                ],
                [
                  "\"f\u0000oo\" becomes \"f\ufffdoo\"",
                  0,
                  null,
                  null
                ],
                [
                  "\"\u0000foo\" becomes \"\ufffdfoo\"",
                  0,
                  null,
                  null
                ],
                [
                  "\"\u0000\" becomes \"\ufffd\"",
                  0,
                  null,
                  null
                ],
                [
                  "\"\u0000\u0000\u0000\" becomes \"\ufffd\ufffd\ufffd\"",
                  0,
                  null,
                  null
                ],
                [
                  "\"fooU+d800\" becomes \"foo\ufffd\"",
                  1,
                  "assert_equals: expected \"foo\\ufffd\" but got \"foo\ud800\"",
                  "    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:40:1"
                ],
                [
                  "\"fU+d800oo\" becomes \"f\ufffdoo\"",
                  1,
                  "assert_equals: expected \"f\\ufffdoo\" but got \"f\ud800oo\"",
                  "    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:41:1"
                ],
                [
                  "\"U+d800foo\" becomes \"\ufffdfoo\"",
                  1,
                  "assert_equals: expected \"\\ufffdfoo\" but got \"\ud800foo\"",
                  "    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:42:1"
                ],
                [
                  "\"U+d800\" becomes \"\ufffd\"",
                  1,
                  "assert_equals: expected \"\\ufffd\" but got \"\ud800\"",
                  "    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:43:1"
                ],
                [
                  "\"U+d800U+d800U+d800\" becomes \"\ufffd\ufffd\ufffd\"",
                  1,
                  "assert_equals: expected \"\\ufffd\\ufffd\\ufffd\" but got \"\ud800\ud800\ud800\"",
                  "    at Test.<anonymous> (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:26:9)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:1908:25)\n    at test (http://web-platform.test:8000/resources/testharness.js:544:30)\n    at testParsing (http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:25:5)\n    at http://web-platform.test:8000/css/css-syntax/input-preprocessing.html:44:1"
                ]
              ]
            ]
          ]
        }
      }
    }
  }
}
```

**Comment by gsnedders** [comment]
See https://bugs.chromium.org/p/chromedriver/issues/detail?id=3169 for ChromeDriver bug.

**Comment by gsnedders** [comment]
Hmmmmmm. So actually every browser fails here. (Firefox only passes because it doesn't pass back the assertion failed messages… because it passes.)

**Comment by tabatkins** [comment]
So would I be able to work around this by changing the test messages to not include surrogates? Or would the fact that a surrogate is in the input still mess things up due to auto-generated messages?

**Comment by tabatkins** [comment]
(I note that the wpt.fyi page seems to serialize the surrogate in the test message as `U+d800`, but it doesn't do the same for the nulls, which is definitely a bit confusing.)

**Comment by gsnedders** [comment]
@tabatkins we should fix this more generally than just here, really; test names we sanitize lone surrogates in but we don't seem to in assertion messages.
