### ISSUE TITLE
/infrastructure/testdriver/actions/actionsWithKeyPressed.html is failing on Azure

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#17635]
The failure seems to be checked into master, but doesn't show up in [the commits](https://github.com/web-platform-tests/wpt/commits/master) as a failure because it gets skipped, e.g. https://github.com/web-platform-tests/wpt/commit/cd18d4954c5184ecfb7a210aa939081c5e2552e8 : https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=22213

> TEST-FAIL | /infrastructure/testdriver/actions/actionsWithKeyPressed.html | TestDriver actions: actions with key pressed - assert_array_equals: lengths differ, expected 3 got 1
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:64:34)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:1611:25)
    at http://web-platform.test:8000/resources/testharness.js:1651:32

https://github.com/web-platform-tests/wpt/commit/29b7c1aeea57ca62dc7c2579a601aba077c1805f is the source of the file.

**Comment by lukebjerring** [comment]
Note that https://github.com/web-platform-tests/wpt/issues/17296 was closed by https://github.com/web-platform-tests/wpt/commit/2e5b9fb08c42966831690bd01b9b6410efc479fa

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/wpt/pull/16475 was the PR that re-landed the test

**Comment by lukebjerring** [comment]
Dupe of https://github.com/web-platform-tests/wpt/issues/17296; likely that new runs aren't afflicted anymore.
