### ISSUE TITLE
Edge Dev jobs are failing on Azure Pipelines

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18044]
https://wpt.fyi has incomplete results from Edge Dev on the front page, currently from commit b4b36aef39d46f9f33effcb6cd0253a81b337818.

The Azure Pipelines build for that was https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=24084&view=logs.

The "all tests: Edge Dev 2" and other jobs finished too fast and didn't run any tests, failing up front like this:
```
Failed to start protocol connection
Traceback (most recent call last):
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\protocol.py", line 48, in setup
    self.connect()
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 228, in connect
    self.webdriver.start()
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 429, in start
    value = self.send_command("POST", "session", body=body)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 480, in send_command
    raise err
UnknownErrorException: unknown error (500): unknown error: Microsoft Edge failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from MicrosoftEdge location C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe is no longer running, so MSEdgeDriver is assuming that Microsoft Edge has crashed.)

Remote-end stacktrace:

Backtrace:
	Ordinal0 [0x00AF7A23+1538595]
	Ordinal0 [0x00A6B5E1+964065]
	Ordinal0 [0x00A00B33+527155]
	Ordinal0 [0x0098EC1E+60446]
	Ordinal0 [0x009B243B+205883]
	Ordinal0 [0x009B1EED+204525]
	Ordinal0 [0x009B051B+197915]
	Ordinal0 [0x009960F6+90358]
	Ordinal0 [0x0099777A+96122]
	Ordinal0 [0x00997674+95860]
	Ordinal0 [0x00A8C867+1099879]
	GetHandleVerifier [0x00BA2925+526933]
	GetHandleVerifier [0x00BA26C0+526320]
	GetHandleVerifier [0x00BA9578+554664]
	GetHandleVerifier [0x00BA30FA+528938]
	Ordinal0 [0x00A81AB6+1055414]
	Ordinal0 [0x00A8192F+1055023]
	Ordinal0 [0x00A8E99B+1108379]
	Ordinal0 [0x00A8EADF+1108703]
	Ordinal0 [0x00A8DA05+1104389]
	BaseThreadInitThunk [0x74C10419+25]
	RtlGetAppContainerNamedObjectPath [0x76F2662D+237]
	RtlGetAppContainerNamedObjectPath [0x76F265FD+189]
```

However, we still finished with an exit code of zero.

@thejohnjansen @mustjab can you take a look at why Edge or EdgeDriver is crashing?

@gsnedders @lukebjerring we might want to prioritize fixing the exit code in cases like this, I've now seen it on both Edge and Safari.

**Comment by thejohnjansen** [comment]
Taking a look... it looks like there hasn't been a run in Edge for about a week, is that because of this issue?

**Comment by foolip** [comment]
That's probably not the reason, no. With this issue, the run finished but was incomplete.

**Comment by foolip** [comment]
https://wpt.fyi/runs has 4 successful Edge Dev runs in a row now.
