### ISSUE TITLE
Edge Canary job failed on shutdown, failing whole run

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18583]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28092 failed the "all tests: Edge Canary 7" job at the very end:
```
TEST-START | /xhr/xmlhttprequest-timeout-abortedonmain.html?abort() from a 0ms timeout
TEST-PASS | /xhr/xmlhttprequest-timeout-abortedonmain.html?abort() from a 0ms timeout | Timeout test: time to abort is 0, timeout set at 2000 
TEST-OK | /xhr/xmlhttprequest-timeout-abortedonmain.html?abort() from a 0ms timeout | took 7764ms
No more tests
Closing logging queue
queue closed
Got 3528 unexpected results
SUITE-END | took 5541s
Closing logging queue
queue closed
##[error]Traceback (most recent call last):
##[error]  File "./wpt", line 5, in <module>
    wpt.main()
  File "C:\Agent\_work\1\s\tools\wpt\wpt.py", line 164, in main
    rv = script(*args, **kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 661, in run
    rv = run_single(venv, **kwargs) > 0
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 668, in run_single
    return wptrunner.start(**kwargs)
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\wptrunner.py", line 344, in start
    return not run_tests(**kwargs)
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\wptrunner.py", line 295, in run_tests
    break
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\environment.py", line 110, in __exit__
    self.stash.__exit__()
  File "C:\Agent\_work\1\s\tools\wptserve\wptserve\stash.py", line 44, in __exit__
    self.manager.shutdown()
  File "C:\Python27\lib\multiprocessing\util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "C:\Python27\lib\multiprocessing\managers.py", line 625, in _finalize_manager
    process.terminate()
  File "C:\Python27\lib\multiprocessing\process.py", line 140, in terminate
    self._popen.terminate()
  File "C:\Python27\lib\multiprocessing\forking.py", line 312, in terminate
    _subprocess.TerminateProcess(int(self._handle), TERMINATE)
WindowsError: [Error 5] Access is denied

##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Run tests (Edge Canary)
```

This is the call site that threw the exception:
https://github.com/web-platform-tests/wpt/blob/e4ba26cf0324af4ffd46607b296f5362243728a3/tools/wptserve/wptserve/stash.py#L44

@mustjab this seems like potentially a problem with the VM setup, or are any incorrect assumptions being made by the wptrunner code here? I've assigned to you, please unassign if that's not OK.

This happened on the second full run after https://github.com/web-platform-tests/wpt/pull/18448 was landed, so it's possible this failure more is made more likely by that change. If it happens again, I think we should revert that change.

**Comment by foolip** [comment]
Every scheduled run after this has been fine, so probably not related to https://github.com/web-platform-tests/wpt/pull/18448. Phew.

**Comment by foolip** [comment]
This happened just once, or at leat I only saw it once.
