### ISSUE TITLE
No recent Edge Dev runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19005]
Edge Dev runs have stopped showing up on https://wpt.fyi/runs. These are the runs we use for the front page of wpt.fyi, so treating this as an urgent issue.

@thejohnjansen @mustjab

**Comment by foolip** [comment]
The recent series of failing builds, starting with earliest:
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30405
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30444
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30470
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30513

Looks like it's always "all tests: Edge Dev 3" failing, and failing quickly after a bit over a minute.

From beginning to end of the logs it's "Failed to create a Microsoft Edge process" like this:
```
Failed to start protocol connection
Traceback (most recent call last):
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\protocol.py", line 48, in setup
    self.connect()
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 230, in connect
    self.webdriver.start()
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 429, in start
    value = self.send_command("POST", "session", body=body)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 480, in send_command
    raise err
UnknownErrorException: unknown error (500): unknown error: Failed to create a Microsoft Edge process.

Remote-end stacktrace:

Backtrace:
	Ordinal0 [0x00B5B7D3+1554387]
	Ordinal0 [0x00AD7F01+1015553]
	Ordinal0 [0x00A5BF5F+507743]
	Ordinal0 [0x009ECFB5+53173]
	Ordinal0 [0x00A0B940+178496]
	Ordinal0 [0x00A0B56D+177517]
	Ordinal0 [0x00A098CB+170187]
	Ordinal0 [0x009F2607+75271]
	Ordinal0 [0x009F3680+79488]
	Ordinal0 [0x009F3619+79385]
	Ordinal0 [0x00AF2B17+1125143]
	GetHandleVerifier [0x00BFB90D+507245]
	GetHandleVerifier [0x00BFB6A0+506624]
	GetHandleVerifier [0x00C0278C+535532]
	GetHandleVerifier [0x00BFC11A+509306]
	Ordinal0 [0x00AE9C4C+1088588]
	Ordinal0 [0x00AF4B7B+1133435]
	Ordinal0 [0x00AF4CE3+1133795]
	Ordinal0 [0x00AF3C75+1129589]
	BaseThreadInitThunk [0x74B10419+25]
	RtlGetAppContainerNamedObjectPath [0x7724662D+237]
	RtlGetAppContainerNamedObjectPath [0x772465FD+189]
```

This was also the error in https://github.com/web-platform-tests/wpt/issues/18044.

**Comment by foolip** [comment]
Like https://github.com/web-platform-tests/wpt/issues/18995 this started happening right after and so the proximate cause is probably https://github.com/web-platform-tests/wpt/pull/18967.

**Comment by foolip** [comment]
In https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30565 it's looking like much more widespread failures. @mustjab I wonder if the agent cluster isn't feeling quite well?

**Comment by mustjab** [comment]
@foolip I did a test run and was able to get the Dev branch run to ocmplete: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30619

Let me know if any future runs fail and i'll try to repro again.
