### ISSUE TITLE
While installing chrome browser, get NotImplementedError

### ISSUE THREAD

**Issue by r12543** [web-platform-tests/wpt#19324]
```
./wpt install chrome browser
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Interpreting channel 'nightly' as 'dev'
Now installing chrome browser...
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/rchaudhary/work/github/wpt/tools/wpt/wpt.py", line 164, in main
    rv = script(*args, **kwargs)
  File "/Users/rchaudhary/work/github/wpt/tools/wpt/install.py", line 76, in run
    install(browser, kwargs["component"], destination, channel)
  File "/Users/rchaudhary/work/github/wpt/tools/wpt/install.py", line 91, in install
    path = getattr(subclass(logger), method)(dest=destination, channel=channel)
  File "/Users/rchaudhary/work/github/wpt/tools/wpt/browser.py", line 474, in install
    raise NotImplementedError
NotImplementedError
```

Any ideas? How to install chrome using wpt?

**Comment by r12543** [comment]
Hi guys, i am still getting this error. Can anyone please clarify this?

**Comment by foolip** [comment]
@r12543 from the paths it looks you're on macOS, is that right?

I'm pretty sure installing Chrome on macOS has never worked, and probably not on Linux either. Instead you'll need to install Chrome on the system.

@jgraham is this the intended failure mode for `./wpt install`, or should there be a nicer message?
