### ISSUE TITLE
Error in ./xhr/resources/access-control-preflight-denied.py

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#20670]
I get this while running the tests:

```
ERROR:web-platform-tests:Traceback (most recent call last):
  File "/home/travis/build/jsdom/jsdom/test/web-platform-tests/tests/tools/wptserve/wptserve/handlers.py", line 314, in __call__
    rv = self.func(request, response)
  File "./xhr/resources/access-control-preflight-denied.py", line 42, in main
    setState("Deny Ignored")
TypeError: setState() takes exactly 2 arguments (1 given)
```

It doesn't appear to prevent the tests from running, but probably someone should look into this?

**Comment by stephenmcgruer** [comment]
cc @annevk @jdm as two folks listed in `xhr/META.yml`

Looks like a bug in the handler, which is test-author written.

**Comment by jdm** [comment]
Agreed. It should pretty clearly be `setState(token, "Deny Ignored")`.
