### ISSUE TITLE
Missing WebkitGTK run for Dec 11th; error setting up virtualenv

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#20742]
This appears like it might be a one-off, but opening for completeness. Yesterday's run of WebkitGTK from the epochs/daily branch didn't complete successfully due to an error setting up virtualenv.

[The epochs task](https://github.com/web-platform-tests/wpt/commit/276ecb946ba74f402adbbc32f6f102b292d333a0/checks?check_suite_id=354291614).

[The Taskcluster task group for that commit](https://community-tc.services.mozilla.com/tasks/groups/ed8cxpcdQW-Q2ql0k6YqXw)

[The failing log](https://community-tc.services.mozilla.com/tasks/aDl04K1MQyKKNtEb5LBhpw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FaDl04K1MQyKKNtEb5LBhpw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log):

```
Collecting setuptools
  Created temporary directory: /tmp/pip-unpack-fFV6LV
  Looking up "https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl" in the cache
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl HTTP/1.1" 200 583156
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-rEL_Yr'
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
```

@jgraham assigning to you since this appears to be a Taskcluster failure rather than anything specific to WebkitGTK. If it seems entirely spurious feel free to close and we'll just keep an eye out for it happening again.

@clopez as an FYI (likely no action needed by you)

**Comment by clopez** [comment]
It aborts in urllib3/response.py likely due to a network error.
The network of the bots runing the taskcluster tests its a bit unreliable. I have already observed this several times, check for example [this comment](https://github.com/web-platform-tests/wpt/issues/20106#issuecomment-554160028)

**Comment by jgraham** [comment]
Do we have any evidence it's actually TaskCluster that's unreliable vs PyPI being unreliable? Apart from running our own PyPI mirror with the deps we need I'm not sure what to do about this.

**Comment by clopez** [comment]
On #19725 I observed the download of the webkitgtk built product from https://webkitgtk.org/built-products/ was unreliable. I workaround-ed it by patching the code to retry the download

**Comment by stephenmcgruer** [comment]
Archiving as inactive; I don't think we're going to take any action here (aside from the retry logic clopez added)
