### ISSUE TITLE
AssertionError from mozlog when running a failing reftest multiple times

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#20866]
To reproduce:

```bash
./wpt run --log-mach - --repeat 3 chrome infrastructure/reftest/reftest_and_fail.html
```

(The browser doesn't matter; you can also reproduce the issue with Firefox.)

In the logs, you can see that the Nth iteration has N `FAIL` in `TEST_END`, which then triggers an assertion error in mozlog:
```
0:07.79 INFO Repetition 2 / 2
...
0:10.78 TEST_START: /infrastructure/reftest/reftest_and_fail.html
...
0:19.48 TEST_END: FAIL, expected PASS
FAIL /infrastructure/reftest/reftest_and_fail.html - Testing http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail.html == http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail_0-ref.html
Testing http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail_0-ref.html == http://web-platform.test:8000/infrastructure/reftest/red.html
Found 480000 pixels different, maximum difference per channel 255
FAIL /infrastructure/reftest/reftest_and_fail.html - Testing http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail.html == http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail_0-ref.html
Testing http://web-platform.test:8000/infrastructure/reftest/reftest_and_fail_0-ref.html == http://web-platform.test:8000/infrastructure/reftest/red.html
Found 480000 pixels different, maximum difference per channel 255
...
mozlog.structuredlog: Failure calling log handler:
Traceback (most recent call last):
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/structuredlog.py", line 274, in _handle_log
    handler(data)
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/handlers/base.py", line 74, in __call__
    formatted = self.formatter(data)
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/handlers/base.py", line 42, in __call__
    return self.inner(item)
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/formatters/machformatter.py", line 88, in __call__
    s = super(MachFormatter, self).__call__(data)
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/reader.py", line 74, in __call__
    return handler(data)
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/formatters/machformatter.py", line 137, in suite_end
    self.summary.current))
  File "/usr/local/google/home/robertma/github/wpt/_venv/lib/python2.7/site-packages/mozlog/formatters/machformatter.py", line 255, in _format_suite_summary
    assert len(results) == 1
AssertionError
```

It seems like we do not clear the test results between each iteration. This issue might have been around for a while.

**Comment by jgraham** [comment]
I think this is a bug in mozlog. The summary handler isn't really handling the case of the same test being rerun multiple times. I'll file a bugzilla issue for it.

**Comment by jgraham** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1605731

**Comment by Hexcles** [comment]
Looks like the bug has been fixed in m-c. Is there anything we need to do to roll this change in?

**Comment by stephenmcgruer** [comment]
We updated mozlog to 6.0, and I cannot reproduce using the command line in the original comment. I assume this is fixed.
