### ISSUE TITLE
Safari builds fail on pointerevents/pointerevent_pointercapture_in_frame.html

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#20887]
The failures in https://github.com/web-platform-tests/wpt/pull/20878 are partly due to this test hitting an external timeout, perhaps safaridriver has gotten into a bad state. From the logs:

```
2019-12-19T22:20:05.9720940Z /pointerevents/compat/pointerevent_touch-action_two-finger_interaction.html
2019-12-19T22:20:05.9721670Z   ERROR /pointerevents/compat/pointerevent_touch-action_two-finger_interaction.html - Traceback (most recent call last):
2019-12-19T22:20:05.9721950Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 317, in run_func
2019-12-19T22:20:05.9722170Z     self.result = True, self.func(self.protocol, self.url, self.timeout)
2019-12-19T22:20:05.9722360Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 410, in do_testharness
2019-12-19T22:20:05.9722550Z     done, rv = handler(result)
2019-12-19T22:20:05.9722820Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 700, in __call__
2019-12-19T22:20:05.9723010Z     return callback(url, payload)
2019-12-19T22:20:05.9723190Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 714, in process_action
2019-12-19T22:20:05.9723370Z     result = action_handler(payload)
2019-12-19T22:20:05.9723540Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 773, in __call__
2019-12-19T22:20:05.9723740Z     self.protocol.action_sequence.send_actions({"actions": actions})
2019-12-19T22:20:05.9723910Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 189, in send_actions
2019-12-19T22:20:05.9724470Z     self.webdriver.actions.perform(actions['actions'])
2019-12-19T22:20:05.9724790Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 19, in inner
2019-12-19T22:20:05.9724980Z     return func(self, *args, **kwargs)
2019-12-19T22:20:05.9725170Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 220, in perform
2019-12-19T22:20:05.9725350Z     actions = self.session.send_session_command("POST", "actions", body)
2019-12-19T22:20:05.9725530Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 515, in send_session_command
2019-12-19T22:20:05.9725710Z     return self.send_command(method, url, body)
2019-12-19T22:20:05.9725900Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 479, in send_command
2019-12-19T22:20:05.9726080Z     raise err
2019-12-19T22:20:05.9726240Z WebDriverException: not implemented (501):
2019-12-19T22:20:05.9726400Z /pointerevents/pointerevent_pointercapture_in_frame.html
2019-12-19T22:20:05.9727000Z   TIMEOUT /pointerevents/pointerevent_pointercapture_in_frame.html - Executor hit external timeout (this may indicate a hang)
2019-12-19T22:20:05.9727270Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 774, in __bootstrap
2019-12-19T22:20:05.9727460Z     self.__bootstrap_inner()
2019-12-19T22:20:05.9727630Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2019-12-19T22:20:05.9727830Z     self.run()
2019-12-19T22:20:05.9728000Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
2019-12-19T22:20:05.9728460Z     self.__target(*self.__args, **self.__kwargs)
2019-12-19T22:20:05.9728650Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 317, in run_func
2019-12-19T22:20:05.9728850Z     self.result = True, self.func(self.protocol, self.url, self.timeout)
2019-12-19T22:20:05.9729040Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 410, in do_testharness
2019-12-19T22:20:05.9729220Z     done, rv = handler(result)
2019-12-19T22:20:05.9729400Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 700, in __call__
2019-12-19T22:20:05.9729570Z     return callback(url, payload)
2019-12-19T22:20:05.9729750Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 714, in process_action
2019-12-19T22:20:05.9729940Z     result = action_handler(payload)
2019-12-19T22:20:05.9730110Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 773, in __call__
2019-12-19T22:20:05.9730320Z     self.protocol.action_sequence.send_actions({"actions": actions})
2019-12-19T22:20:05.9730500Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 189, in send_actions
2019-12-19T22:20:05.9731210Z     self.webdriver.actions.perform(actions['actions'])
2019-12-19T22:20:05.9731640Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 19, in inner
2019-12-19T22:20:05.9731860Z     return func(self, *args, **kwargs)
2019-12-19T22:20:05.9732030Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 220, in perform
2019-12-19T22:20:05.9732220Z     actions = self.session.send_session_command("POST", "actions", body)
2019-12-19T22:20:05.9732410Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 515, in send_session_command
2019-12-19T22:20:05.9732620Z     return self.send_command(method, url, body)
2019-12-19T22:20:05.9732800Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/client.py", line 470, in send_command
2019-12-19T22:20:05.9732970Z     session=self)
2019-12-19T22:20:05.9733150Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/transport.py", line 175, in send
2019-12-19T22:20:05.9733350Z     response = self._request(method, uri, payload, headers)
2019-12-19T22:20:05.9733530Z   File "/Users/runner/runners/2.163.1/work/1/s/tools/webdriver/webdriver/transport.py", line 191, in _request
2019-12-19T22:20:05.9733720Z     return self.connection.getresponse()
2019-12-19T22:20:05.9733880Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1148, in getresponse
2019-12-19T22:20:05.9734080Z     response.begin()
2019-12-19T22:20:05.9734270Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 448, in begin
2019-12-19T22:20:05.9734470Z     version, status, reason = self._read_status()
2019-12-19T22:20:05.9734670Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 404, in _read_status
2019-12-19T22:20:05.9734850Z     line = self.fp.readline(_MAXLINE + 1)
2019-12-19T22:20:05.9735030Z   File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
2019-12-19T22:20:05.9735230Z     data = self._sock.recv(self._rbufsize)
2019-12-19T22:20:05.9735400Z CRITICAL Max restarts exceeded
2019-12-19T22:20:05.9735560Z ERROR Unsupported test type crashtest for product safari
2019-12-19T22:20:05.9735740Z 64:11.98 INFO Closing logging queue
2019-12-19T22:20:05.9735890Z 64:11.99 INFO queue closed
2019-12-19T22:20:05.9736050Z 64:11.99 INFO Tolerating 52022 unexpected results
```

pointerevents/compat/pointerevent_touch-action_two-finger_interaction.html is also in the logs, but it's probably not the cause.

**Comment by Hexcles** [comment]
The fix worked: https://wpt.fyi/results/?run_id=390460003
