### ISSUE TITLE
'CRITICAL Max restarts exceeded' for edge WPT run command

### ISSUE THREAD

**Issue by NbhosaleInstart** [web-platform-tests/wpt#21430]
On running the wpt run command on **Windows 10 for Edge browser**, we are getting a **Max restarts exceeded** error and the tests are not running.
>python wpt.py run --headless edge js
>Running 14 tests in web-platform-tests
>
>CRITICAL Max restarts exceeded
>ERROR Unsupported test type crashtest for product edge
>Ran 0 tests finished in 18.5 seconds.
>  ΓÇó 0 ran as expected. 0 tests skipped.
>
>CRITICAL No tests ran

**Edge and corresponding driver version** used- 79.0.309.71 (Official build) (64-bit)

Windows OS specs-
>Edition            Windows 10 Home Single Language
>Version           1903
>OS build         18362.592
>System-type   64-bit OS

**What should be causing this error? OR, alternatively, may I know which version of edge can get the tests to work?**

Note- There is also a bug, wherein inspite of having `--headless` as an option, the Edge browser windows get opened and do not get closed. PFA screenshot, although this is of less priority than the actual `max restarts exceeded` issue.

![Annotation 2020-01-24 151433](https://user-images.githubusercontent.com/60255297/73162892-d06a4c00-4114-11ea-807f-f175c40b8968.png)

**Comment by gsnedders** [comment]
@NbhosaleInstart 

The "edge" product refers to the (legacy) EdgeHTML-based Edge; the "edgechromium" is what you want for current Edge release.

**Comment by stephenmcgruer** [comment]
@mustjab (as the only MSer I know the GitHub username of offhand ;)) - do you think we should be updating wpt such that 'edge' refers to 'edgechromium' nowadays (and maybe introduce 'edgehtml' or just drop that entirely), or is the nomenclature on the technical side still that 'edge' refers to EdgeHTML?

**Comment by mustjab** [comment]
We can use “Edge (EdgeHTML)” and “Edge (Chromium)”, let me know if that works.

cc: @thejohnjansen

**Comment by stephenmcgruer** [comment]
Well this is on the command line; the question is should `wpt run edge` run Edge (EdgeHTML) or Edge (Chromium)? (Currently the former, but clearly causing confusion)

**Comment by mustjab** [comment]
I see. For command line I think your proposal to rename edge to edgehtml and change edge to refer to edgechromium should work. The edgehtml run don't need to happen on a daily basis as we're only making servicing fixes there and are not actively adding features or modifying platform.

**Comment by gsnedders** [comment]
note also https://github.com/web-platform-tests/wpt/issues/16054, about `edge_webdriver`. I guess we want to rename `edge_webdriver` to `edgehtml` and `edgechromium` to `edge` (and get rid of the current `edge`).

**Comment by NbhosaleInstart** [comment]
> @NbhosaleInstart
> 
> The "edge" product refers to the (legacy) EdgeHTML-based Edge; the "edgechromium" is what you want for current Edge release.

@gsnedders , thanks for the clarification. Tried edgechromium, getting the following error.
Any insights on this?

**(wpt_env) C:\Instart\nv-web-platform-tests\wpt>python wpt.py run edgechromium js --log-wptreport=../report/edgechromium.json
Running 14 tests in web-platform-tests

Socket error on port 8443
Process https on port 8443:
Traceback (most recent call last):
  File "c:\python27\Lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "c:\python27\Lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Instart\nv-web-platform-tests\wpt\tools\serve\serve.py", line 419, in create_daemon
    self.daemon = init_func(host, port, paths, routes, bind_address, config, **kwargs)
  File "C:\Instart\nv-web-platform-tests\wpt\tools\serve\serve.py", line 566, in start_https_server
    latency=kwargs.get("latency"))
  File "C:\Instart\nv-web-platform-tests\wpt\tools\wptserve\wptserve\server.py", line 674, in __init__
    http2=http2)
  File "C:\Instart\nv-web-platform-tests\wpt\tools\wptserve\wptserve\server.py", line 181, in __init__
    BaseHTTPServer.HTTPServer.__init__(self, hostname_port, request_handler_cls, **kwargs)
  File "c:\python27\Lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "c:\python27\Lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "c:\python27\Lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "c:\python27\Lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
[17156:17192:0210/175616.075:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
[10448:13436:0210/175621.029:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
[16596:860:0210/175623.891:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
[4172:16136:0210/175626.660:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
CRITICAL Max restarts exceeded
ERROR Unsupported test type crashtest for product edgechromium
Ran 0 tests finished in 15.2 seconds.
  ΓÇó 0 ran as expected. 0 tests skipped.

CRITICAL No tests ran**

**Comment by stephenmcgruer** [comment]
@NbhosaleInstart sorry for the delay in replying here. Two questions:

1. Have you followed the setup steps in https://web-platform-tests.org/running-tests/from-local-system.html ?
1. Could there be another process running which has a service bound on port 8443?

**Comment by stephenmcgruer** [comment]
Closing due to lack of activity.
