### ISSUE TITLE
[Windows] `wpt run firefox/chrome` fails on Python 3.7

### ISSUE THREAD

**Issue by saschanaz** [web-platform-tests/wpt#22316]
```
$ python3 wpt run firefox dom/historical.html
Traceback (most recent call last):
  File "wpt", line 12, in <module>
    wpt.main()
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wpt\wpt.py", line 167, in main
    rv = script(*args, **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wpt\run.py", line 806, in run
    rv = run_single(venv, **kwargs) > 0
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wpt\run.py", line 813, in run_single
    return wptrunner.start(**kwargs)
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\wptrunner.py", line 378, in start
    rv = not run_tests(**kwargs) or logged_critical.has_log
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\wptrunner.py", line 182, in run_tests
    **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\wptrunner.py", line 58, in get_loader
    enable_webrender=kwargs.get("enable_webrender"))
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\wpttest.py", line 82, in get_run_info
    return RunInfo(metadata_root, product, **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\wpttest.py", line 99, in __init__
    rev = GitTree(log_error=False).rev
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\update\tree.py", line 174, in rev
    if vcs.is_git_root(self.root):
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\vcs.py", line 57, in is_git_root
    rv = git("rev-parse", "--show-cdup", repo=path, log_error=log_error)
  File "c:\Users\Kagami\Documents\GitHub\web-platform-tests\tools\wptrunner\wptrunner\vcs.py", line 36, in inner
    return func(command_line, stderr=subprocess.STDOUT, **proc_kwargs)
  File "c:\mozilla-build\python3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\mozilla-build\python3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\mozilla-build\python3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\mozilla-build\python3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
TypeError: CreateProcess() argument 8 must be str or None, not bytes
```

**Comment by stephenmcgruer** [comment]
cc @ziransun and @svillar who have been doing work in this area recently, though they have explicitly been focusing on chrome support due to many Py3 bugs trying to get Firefox working. I believe those bugs were in moz-libraries, though here the code looks (at first glance) product agnostic.

Perhaps it is relating to browser download support (known to not work yet) or to Windows specifically. Would need to dig into the stacktrace.

**Comment by svillar** [comment]
checking...

**Comment by svillar** [comment]
I cannot exactly reproduce your issue, but I'm getting similar errors in some other parts. The problem is that for Firefox the code is using the Marionette driver, which is not completely ported to Python3. See for example [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1597687).

**Comment by saschanaz** [comment]
>The problem is that for Firefox the code is using the Marionette driver

I guess my specific error does not touch any Firefox code though, as it also happens when using Chrome:

```
$ python3 wpt run chrome dom/historical.html
Traceback (most recent call last):
  File "wpt", line 12, in <module>
    wpt.main()
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wpt\wpt.py", line 167, in main
    rv = script(*args, **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wpt\run.py", line 806, in run
    rv = run_single(venv, **kwargs) > 0
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wpt\run.py", line 813, in run_single
    return wptrunner.start(**kwargs)
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\wptrunner.py", line 378, in sta
rt
    rv = not run_tests(**kwargs) or logged_critical.has_log
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\wptrunner.py", line 182, in run
_tests
    **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\wptrunner.py", line 58, in get_
loader
    enable_webrender=kwargs.get("enable_webrender"))
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\wpttest.py", line 82, in get_ru
n_info
    return RunInfo(metadata_root, product, **kwargs)
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\wpttest.py", line 99, in __init
__
    rev = GitTree(log_error=False).rev
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\update\tree.py", line 174, in r
ev
    if vcs.is_git_root(self.root):
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\vcs.py", line 57, in is_git_roo
t
    rv = git("rev-parse", "--show-cdup", repo=path, log_error=log_error)
  File "c:\Users\Kagami\Documents\GitHub\gecko-dev\testing\web-platform\tests\tools\wptrunner\wptrunner\vcs.py", line 36, in inner
    return func(command_line, stderr=subprocess.STDOUT, **proc_kwargs)
  File "c:\mozilla-build\python3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\mozilla-build\python3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\mozilla-build\python3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\mozilla-build\python3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
TypeError: CreateProcess() argument 8 must be str or None, not bytes
```

**Comment by svillar** [comment]
Ah you're in Windows (sorry I was just checking the method names in the backtrace). I found a similar error recently, some calls in Windows (even from the standard library) have different preconditions than POSIX platforms.

Mind telling me which commit/tag of wpt are you exactly using? I ask because I can reproduce many other py3 issues in Windows but not exactly yours.

**Comment by saschanaz** [comment]
>Mind telling me which commit/tag of wpt are you exactly using? I ask because I can reproduce many other py3 issues in Windows but not exactly yours.

I tried this on the latest master branch. It seems this happens exclusively on Python 3.7 bundled with MozillaBuild but not on Python 3.8 from Microsoft Store. Not sure why...

**Comment by svillar** [comment]
> > Mind telling me which commit/tag of wpt are you exactly using? I ask because I can reproduce many other py3 issues in Windows but not exactly yours.
> 
> I tried this on the latest master branch. It seems this happens exclusively on Python 3.7 bundled with MozillaBuild but not on Python 3.8 from Microsoft Store. Not sure why...

Yeah, as I mentioned in a previous comment, python implementations are unfortunately different per-platform. And with different I actually mean incompatible as they do not have the same preconditions.

In any case it's a good heads up for us. It looks like windows requires some python3 love.

**Comment by stephenmcgruer** [comment]
Downgrading to backlog as currently the wptserve work is taking up all of our available Python 3 bandwidth. Once that's done we may return to windows issues.

**Comment by ziransun** [comment]
This seems having been solved. I just tested on chrome and firefox using python 3.7.5. Both tests ran fine. Please let me know if you still have issue with python 3.7.

**Comment by saschanaz** [comment]
Yes, I'm now on Python 3.9 and it works without any problem.
