### ISSUE TITLE
No Chrome stable runs since April 7th

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#22879]
According to https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari, wpt.fyi has not received a Chrome stable run since April 7th. Firefox and Safari seem fine.

Similarly (but not necessarily related), there have been no Chrome experimental runs since April 9th.

**Comment by stephenmcgruer** [comment]
https://community-tc.services.mozilla.com/tasks/groups/Cxf23J2FT9GLA-nlF506ug is the TC run for `epochs/daily` for April 11th. It contains multiple Chrome task failures, all of which occur whilst downloading Chrome:

```
Traceback (most recent call last):
  File "./tools/ci/run_tc.py", line 486, in <module>
    main()
  File "./tools/ci/run_tc.py", line 478, in main
    setup_environment(args)
  File "./tools/ci/run_tc.py", line 320, in setup_environment
    install_chrome(args.channel)
  File "./tools/ci/run_tc.py", line 155, in install_chrome
    f.write(resp.read())
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 607, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
```

I suspect this is https://github.com/web-platform-tests/wpt/issues/21529 and we're seeing either TaskCluster's network or dl.google.com becoming badly flaky.

cc @Hexcles and @jgraham

**Comment by stephenmcgruer** [comment]
Confirmed the same problem affected the runs on April 12th, 10th, and 9th, so I'm confident in the network issues hypothesis.

**Comment by guest271314** [comment]
Could "extra scrutiny of M83 release" be a possible reason?

**Comment by foolip** [comment]
This has been resolved.
