### ISSUE TITLE
update-built-tests.sh doesn't work on macOS

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23292]
On macOS 10.15.4 with the system python (2.7.16) and python3 (3.7.3) I get the following error trying to run `./update-built-tests.sh`:
```
+ 2dcontext/tools/build.sh
+ cd 2dcontext/tools
+ virtualenv -p python .virtualenv
Running virtualenv with interpreter /usr/bin/python
Already using interpreter /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
New python executable in /Users/foolip/web-platform-tests/wpt/2dcontext/tools/.virtualenv/bin/python
Installing setuptools, pip, wheel...
done.
+ .virtualenv/bin/pip install pyyaml cairocffi
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Users/foolip/Library/Caches/pip/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2/PyYAML-5.3.1-cp27-cp27m-macosx_10_15_x86_64.whl
Processing /Users/foolip/Library/Caches/pip/wheels/18/bd/38/34f8392fd4c16c8ec9e9506a61444d1b24d9f3b9add979213e/cairocffi-0.9.0-py2-none-any.whl
Collecting cffi>=1.1.0
  Using cached cffi-1.14.0-cp27-cp27m-macosx_10_9_x86_64.whl (173 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pyyaml, pycparser, cffi, cairocffi
Successfully installed cairocffi-0.9.0 cffi-1.14.0 pycparser-2.20 pyyaml-5.3.1
+ .virtualenv/bin/python gentest.py
Traceback (most recent call last):
  File "gentest.py", line 1, in <module>
    from gentestutils import genTestUtils
  File "/Users/foolip/web-platform-tests/wpt/2dcontext/tools/gentestutils.py", line 47, in <module>
    import cairocffi as cairo
  File "/Users/foolip/web-platform-tests/wpt/2dcontext/tools/.virtualenv/lib/python2.7/site-packages/cairocffi/__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "/Users/foolip/web-platform-tests/wpt/2dcontext/tools/.virtualenv/lib/python2.7/site-packages/cairocffi/__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
```

@Hexcles could you check if it works for you? I used to have python3 installed via Homebrew so it could also be that my system is messed up, although here the problem seems to be in the python2 bits...

**Comment by stephenmcgruer** [comment]
Ping for @Hexcles to check please :)

**Comment by stephenmcgruer** [comment]
Ping @Hexcles again, but also @foolip does this still not work for you?

**Comment by Hexcles** [comment]
I screwed up my local Python setup, too and forgot to check back after I fixed it. Sorry.

And the answer is no; I am seeing the same error.

**Comment by Hexcles** [comment]
I don't think Cairo is available on macOS by default. And the official installation instruction uses MacPort: https://www.cairographics.org/download/

**Comment by stephenmcgruer** [comment]
So this is essentially a dupe of https://github.com/web-platform-tests/wpt/issues/19780 then?

**Comment by Hexcles** [comment]
There might be more issues after that. From the looks of it, not many
people ever run this on macOS...

**Comment by stephenmcgruer** [comment]
Reasonable. I don't think we're going to prioritize fixing this, so marking backlog. Anyone interested is of course welcome to pick this up and fix it :)
