### ISSUE TITLE
Servo's glibc and glibcxx dependencies are missing in docker

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#24607]
```
 0:01.00 INFO Installing browser
/home/test/web-platform-tests/_venv2/servo/servo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/test/web-platform-tests/_venv2/servo/servo)
/home/test/web-platform-tests/_venv2/servo/servo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/test/web-platform-tests/_venv2/servo/servo)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/test/web-platform-tests/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 803, in run
    **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 787, in setup_wptrunner
    webdriver_binary=kwargs.get("webdriver_binary"),
  File "/home/test/web-platform-tests/tools/wpt/browser.py", line 1167, in version
    output = call(binary, "--version")
  File "/home/test/web-platform-tests/tools/wpt/utils.py", line 51, in call
    return subprocess.check_output(args).decode('utf8')
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('/home/test/web-platform-tests/_venv2/servo/servo', '--version')' returned non-zero exit status 1
```
I'll keep tinkering with the docker image locally and figure out how to address this.

**Comment by stephenmcgruer** [comment]
Is there a `servo` package we could install directly that could take care of this for us? We do this for `firefox` IIRC since it turned out to be too difficult to keep track of the dependencies it needed.

**Comment by jdm** [comment]
There is no such thing at the moment, unfortunately.
