### ISSUE TITLE
Exception: unable to find test window

### ISSUE THREAD

**Issue by samanthacorrea** [web-platform-tests/wpt#24683]
Could anybody help me, please?

I did some tests in a Raspberry Pi and it shows this result:

  �^v� ERROR [expected OK] /css/css-ui/parsing/box-sizing-computed.html
  �^t^t   �^f^r unable to find test window
Traceback (most recent call last):
  File "/sandbox/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 345, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/sandbox/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 417, in do_testharness
    timeout=5*self.timeout_multiplier)
  File "/sandbox/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 157, in get_test_window
    raise Exception("unable to find test window")
Exception: unable to find test window

On my local machine it's everything ok.

**Comment by stephenmcgruer** [comment]
@samanthacorrea can you give us the exact command-line instruction you are using, and the full log output?
