### ISSUE TITLE
[Python3] Make HTTP/2.0 support Python 3 compatible

### ISSUE THREAD

**Issue by ziransun** [web-platform-tests/wpt#24733]
Running HTTP/2.0 related tests, e.g. http2 tests in `infrastructure/server/ `,  got 

 `WARNING Cannot start HTTP/2.0 server as the environment is not compatible. Requires Python 2.7.10+ (< 3.0) and OpenSSL 1.0.2+` 

Tests returned with
```
ERROR, expected OK - javascript error: window.__wptrunner_process_next_event is not a function
JavaScript stack:
TypeError: window.__wptrunner_process_next_event is not a function
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:7:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:9:4)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: chrome=84.0.4143.2)

```
and

```
Traceback (most recent call last):
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 345, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 430, in do_testharness
    result = protocol.base.execute_script(
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 47, in execute_script
    return method(script)
  File "/wpt/tools/webdriver/webdriver/client.py", line 19, in inner
    return func(self, *args, **kwargs)
  File "/wpt/tools/webdriver/webdriver/client.py", line 648, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
  File "/wpt/tools/webdriver/webdriver/client.py", line 514, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/wpt/tools/webdriver/webdriver/client.py", line 478, in send_command
    raise err
webdriver.error.JavascriptErrorException: javascript error (500): javascript error: window.__wptrunner_process_next_event is not a function
JavaScript stack:
TypeError: window.__wptrunner_process_next_event is not a function
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:7:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:9:4)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: chrome=84.0.4143.2)

Remote-end stacktrace:

#0 0x56298d3367a9 <unknown>

```

We might need to check if all our HTTP/2.0 dependencies are Python3 compatible.

**Comment by stephenmcgruer** [comment]
cc @jgraham who added http2 support - I vaguely recall at the time that it was explicitly py2 only, but can't recall the reason. (Or maybe I'm just totally misremembering! :D)

**Comment by jgraham** [comment]
I don't remember either :) It may just be that we didn't support Py 3 at all when that was added. I'm pretty sure the underlying libraries will support 3, so I'd try just changing he condition to allow any Py ≥ 3.6, which I think matches the OpenSSL requirements.

**Comment by stephenmcgruer** [comment]
Sounds good - @ziransun can you try changing `http2_compatible` in `tools/wptserve/wptserve/utils.py` to allow Py >= 3.6 and see if that works?

**Comment by ziransun** [comment]
> Sounds good - @ziransun can you try changing `http2_compatible` in `tools/wptserve/wptserve/utils.py` to allow Py >= 3.6 and see if that works?

I had changed the condition with the above line and also some minor changes at wptserve side, e.g. `H2Headers` and `H2HandlerCopy` in `server.py` etc. to get rid of some complaints during the run. Unfortunately, tests still ended up with similar errors:

```
TEST_END: ERROR, expected OK - javascript error: window.__wptrunner_process_next_event is not a function
JavaScript stack:
TypeError: window.__wptrunner_process_next_event is not a function
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:7:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:9:4)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: chrome=84.0.4143.2)
Traceback (most recent call last):
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 345, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 430, in do_testharness
    result = protocol.base.execute_script(
  File "/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 47, in execute_script
    return method(script)
  File "/wpt/tools/webdriver/webdriver/client.py", line 19, in inner
    return func(self, *args, **kwargs)
  File "/wpt/tools/webdriver/webdriver/client.py", line 648, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
  File "/wpt/tools/webdriver/webdriver/client.py", line 514, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/wpt/tools/webdriver/webdriver/client.py", line 478, in send_command
    raise err
webdriver.error.JavascriptErrorException: javascript error (500): javascript error: window.__wptrunner_process_next_event is not a function
JavaScript stack:
TypeError: window.__wptrunner_process_next_event is not a function
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:7:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:9:4)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:447:22)
    at <anonymous>:461:23
    at <anonymous>:462:3
  (Session info: chrome=84.0.4143.2)

Remote-end stacktrace:

#0 0x5570b10da7a9 <unknown>
```

**Comment by ziransun** [comment]
https://github.com/web-platform-tests/wpt/pull/25929
