### ISSUE TITLE
chrome nightly test runs failed

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#24753]
```
 0:00.78 INFO Downloading chromedriver
 0:00.87 INFO Downloading ChromeDriver from https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/test/web-platform-tests/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 815, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 783, in setup_wptrunner
    setup_cls.setup(kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 177, in setup
    self.setup_kwargs(kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 337, in setup_kwargs
    browser_binary=kwargs["binary"],
  File "/home/test/web-platform-tests/tools/wpt/browser.py", line 694, in install_webdriver
    self.version(browser_binary), dest)
  File "/home/test/web-platform-tests/tools/wpt/browser.py", line 681, in install_webdriver_by_version
    assert unzipped_path is not None
AssertionError
```
This is likely a regression from the changes in #24673.

**Comment by jdm** [comment]
Then again, https://github.com/web-platform-tests/wpt/commits/epochs/daily shows that the first test run that failed was on https://github.com/web-platform-tests/wpt/commit/d047c507f134899be6f0bde7a48c630ab67fe34a, rather than https://github.com/web-platform-tests/wpt/commit/f50b52910ea6db5d8306f6653fcd1bf752f23698.

**Comment by stephenmcgruer** [comment]
cc @LukeZielinski as an fyi (since they are eco-infra rotation sheriff this week).

@Hexcles - could this relate to the changes you made to webdriver? It seems to be consistent; there were epochs/daily branches over the weekend (e.g. 5ccde40) that failed with the same error.

**Comment by Hexcles** [comment]
This was an incidental regression caused by #24702 and probably only affects Chrome Stable. Fix is on the way.
