### ISSUE TITLE
Marionette driver throws uncaught exception for connection failures

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#25012]
Discovered in https://community-tc.services.mozilla.com/tasks/groups/JpLXfa2_SsmdnWHaKNLpiw , the following command throws an uncaught exception:

```
$ ./wpt --py3 run --log-mach=- --channel=nightly --binary=~/firefox-nightly/firefox firefox infrastructure/server/http2-context.sub.h2.any.html
...
 0:04.82 WARNING Cannot start HTTP/2.0 server as the environment is not compatible. Requires Python 2.7.10+ (< 3.0) and OpenSSL 1.0.2+
...
 0:12.18 TEST_START: /infrastructure/server/http2-context.sub.h2.any.html
 0:12.52 CRITICAL Loading initial page https://web-platform.test:9000/testharness_runner.html failed. Ensure that the there are no other programs bound to this port and that your firewall rules or network setup does not prevent access.
Traceback (most recent call last):
  File "/home/smcgruer/github/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 162, in load_runner
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/home/smcgruer/github/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 210, in dismiss_alert
    f()
  File "/home/smcgruer/github/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 162, in <lambda>
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/home/smcgruer/github/wpt/_venv3/lib/python3.8/site-packages/marionette_driver/marionette.py", line 1468, in navigate
    self._send_message("WebDriver:Navigate",
  File "/home/smcgruer/github/wpt/_venv3/lib/python3.8/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/home/smcgruer/github/wpt/_venv3/lib/python3.8/site-packages/marionette_driver/marionette.py", line 602, in _send_message
    self._handle_error(err)
  File "/home/smcgruer/github/wpt/_venv3/lib/python3.8/site-packages/marionette_driver/marionette.py", line 622, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
marionette_driver.errors.UnknownException: Reached error page: about:neterror?e=connectionFailure&u=https%3A//web-platform.test%3A9000/testharness_runner.html&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20web-platform.test%3A9000.
stacktrace:
        WebDriverError@chrome://marionette/content/error.js:175:5
        UnknownError@chrome://marionette/content/error.js:482:5
        handleReadyState@chrome://marionette/content/listener.js:300:13
        handleEvent@chrome://marionette/content/listener.js:266:14
```

It is true that the test should fail in python 3, because the h2 server cannot be brought up, but this shouldn't cause the runner to crash.

cc @jgraham

**Comment by foolip** [comment]
@stephenmcgruer would you mind giving this a priority label?

**Comment by stephenmcgruer** [comment]
This is a bit of a pain. When using webdriver (for Chrome/etc), we actually run into the same problem (the page can't load) but don't notice during `setup()`. Instead we discover it later when running the test, at which point we convert it to a test ERROR result. Marionette is smarter, however, and fails during `setup()` when we don't have the ability to do such a thing, we just bail.

That said, I think we should actually just skip h2 tests if h2 isn't supported, which lets us keep this defensive behavior in marionette.
