### ISSUE TITLE
"tools/wpt/ tests: Windows" and "tools/ unittests: Windows + Python 3.8" fail on Azure Pipelines

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#26131]
These two tests have been failing consistently on Azure Pipelines. e.g. 
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56032&view=logs&j=47b03e2b-d31e-537f-c8cf-66c80d147ca1
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56041&view=logs&j=802ce073-f5e3-5667-fac8-56b586b322fa

The failures all seem similar.

"tools/wpt/ tests: Windows":
> test_run_verify_unstable
> CRITICAL Max restarts exceeded
> CRITICAL No tests ran

"tools/ unittests: Windows + Python 3.8":
> Traceback (most recent call last):
>  File "D:\a\1\s\tools\ci\tests\..\pr_preview.py", line 18, in <module>
>    import requests
> ModuleNotFoundError: No module named 'requests'

**Comment by Hexcles** [comment]
There are a bunch of issues.

1. Re the `requests` library: virtualenv created by tox wasn't being respected in the test. This is likely https://bugs.python.org/issue38905 and I have a tentative fix in #26267 which replaces the hardcoded `python` with `sys.executable`.
2. Re the more mysterious `tools/wpt` failure, I have the full logs from wptrunner: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56463&view=logs&j=3cbe1e9e-37dd-5d57-923f-2a18a6d81786&t=0a2b014d-9e02-5b85-0f63-5d8fe7679ef1&l=144

```
 2:43.21 WARNING Failed to start protocol connection
 2:43.21 WARNING Traceback (most recent call last):
  File "D:\a\1\s\tools\wptrunner\wptrunner\executors\protocol.py", line 47, in setup
    self.connect()
  File "D:\a\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 312, in connect
    self.webdriver.start()
  File "D:\a\1\s\tools\webdriver\webdriver\client.py", line 457, in start
    value = self.send_command("POST", "session", body=body)
  File "D:\a\1\s\tools\webdriver\webdriver\client.py", line 501, in send_command
    session=self, timeout=timeout)
  File "D:\a\1\s\tools\webdriver\webdriver\transport.py", line 233, in send
    response = self._request(method, uri, payload, headers, timeout=None)
  File "D:\a\1\s\tools\webdriver\webdriver\transport.py", line 258, in _request
    response = self.connection.getresponse()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

I'm going to try verbose logging for ChromeDriver as well.
