### ISSUE TITLE
wptserve can fail with "[Errno 24] Too many open files"

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#27072]
Just noticed that when working on improvements for Marionette, and setting up a testcase for Marionette with the `pageLoadStrategy` set to `none`. If a huge amount of WebDriver navigation requests are send in parallel, wptserve will give-up after a short while with serving the wanted URL when it comes from a file on disk (no handler). In such a case it just returns a 404. Manually reloading the page doesn't make a difference.

Trying to get a index list of all the files from the parent directory gives me a 500 error:

```
[Errno 24] Too many open files: '/Users/henrik/code/gecko/testing/marionette/harness/marionette_harness/www/'
Traceback (most recent call last):
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/server.py\", line 287, in finish_handling
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 212, in __call__
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 84, in __call__
File \"/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptserve/wptserve/handlers.py\", line 101, in list_items\nOSError: [Errno 24] Too many open files: '/Users/henrik/code/gecko/testing/marionette/harness/marionette_harness/www/'
```

As @jgraham said on Matrix: It could be a "we should have a size-limited threadpool, rather than try to spawn an indefinite number of threads" bug. If each thread uses a file handle we can certainly leak them.

**Comment by foolip** [comment]
How many requests are needed to trigger this? I guess it won't happen when using `./wpt run`, but could wpt.live be affected by this if it gets enough traffic?

**Comment by whimboo** [comment]
I assume it's OS dependent, and how many files can be open at the same time. When that happened I didn't count. If it's important I would have to check again.

**Comment by foolip** [comment]
I guess my question is if you ran into this while doing something quite normal, so that others might also run into it, or if you think this is exceptional and unlikely to affect contributors just using `./wpt run`?

**Comment by whimboo** [comment]
Actually today I run `wpt` with the `--repeat-until-unexpected` argument to try verifying a fix in Firefox, and this error popped up after only 25 iterations!

Here the command as run from our `mozilla-central` repository:

```
mach wpt --webdriver-binary=target/debug/geckodriver --webdriver-arg=-vv testing/web-platform/tests/webdriver/tests/switch_to_frame/switch.py --repeat-until-unexpected
```

**Comment by jgraham** [comment]
I ran that locally in headless mode (shouldn't make any difference I think). After nearly 500 repetitions the root Python process seemed to have 127 file handles open, and earlier I observed that number going up and down. The child processes seemed to be more stable. So the leak here is either mac-specific (or more serious on mac due to resource limits) or depends on the performance characteristics of your machine. I don't know if it's possible for you to figure out (e.g. using Activity Monitor or lsof) what the open fds are at the point this crashes?

**Comment by whimboo** [comment]
With the above mentioned test for `Switch To Frame` I was also able to see this problem without using any page as served via wptserve. As such I wonder if those two things are different, or if actually wptrunner causes the leakage of file handles, and then wptserve just suffers from it.

Running wpt tests the following stack is reported when the failure occurs:

```
  File "/Users/henrik/code/gecko/testing/web-platform/mach_commands.py", line 502, in run_wpt
    return self.run_web_platform_tests(**params)
  File "/Users/henrik/code/gecko/testing/web-platform/mach_commands.py", line 492, in run_web_platform_tests
    return wpt_runner.run(logger, **params)
  File "/Users/henrik/code/gecko/testing/web-platform/mach_commands_base.py", line 61, in run
    result = wptrunner.start(**kwargs)
  File "/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptrunner/wptrunner/wptrunner.py", line 413, in start
    rv = not run_tests(**kwargs) or logged_critical.has_log
  File "/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptrunner/wptrunner/wptrunner.py", line 341, in run_tests
    manager_group.run(test_type, run_tests)
  File "/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptrunner/wptrunner/testrunner.py", line 899, in run
    manager = TestRunnerManager(self.suite_name,
  File "/Users/henrik/code/gecko/testing/web-platform/tests/tools/wptrunner/wptrunner/testrunner.py", line 331, in __init__
    self.command_queue = mp.Queue()
```

Btw the maximum amount of files that can be opened on MacOS is set to:

```
➜ sysctl kern.maxfiles
kern.maxfiles: 49152
```

Running `lsof` locally with some filters applied I can see a huge number of file handles required by the plugin-container of Firefox (in this case these are my normal 2 instances of Firefox I have open by default):

```
➜ lsof | awk '{print $1}' | uniq -c | sort -rn | head
3323 plugin-co
 729 firefox
 682 firefox
 589 plugin-co
 427 plugin-co
```

But repeating wpt jobs and letting wptrunner to start several Firefox instances in a row I actually wonder if that issue could be caused by an underlying Firefox bug. I'll have a look in a moment in how it behaves when running the tests.

**Comment by jgraham** [comment]
It looks a lot like you're somehow leaking Firefox processes in general and plugin-container processes in specific.

**Comment by whimboo** [comment]
Given that I hit the same problem with other test suites I did a bit of research today. So MacOS limits the amount of open files (file descriptors) by default to 256. And that certainly could cause issues with larger applications.

We already had a [similar fix a while ago for wptrunner](https://bugzilla.mozilla.org/show_bug.cgi?id=1653294). So maybe we do indeed leak sockets when serving pages with wptserve.

**Comment by jgraham** [comment]
I'm not sure this issue is http2 related, so I'll reopen until someone can verify whether or not it's actually fixed.

**Comment by whimboo** [comment]
Just tested again with `head` and it's still failing with the following command:

> python wpt run firefox webdriver/tests/get_element_rect/get.py --repeat-until-unexpected --binary $path_to_firefox
