### ISSUE TITLE
multiTouchPointsReleaseSecondPoint.html infrastructure test failing on Chrome

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#27200]
I'm not sure if something has changed here (in the test? in testdriver? in Chrome itself?), but recently my changes to `tools/` keep triggering failures in multiTouchPointsReleaseSecondPoint.html (e.g. https://community-tc.services.mozilla.com/tasks/Clz4V0WiQ9aYFXaIOJsQiw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FClz4V0WiQ9aYFXaIOJsQiw%2Fruns%2F0%2Fartifacts%2Fpublic%252Flogs%252Flive.log):

```
/infrastructure/testdriver/actions/multiTouchPointsReleaseSecondPoint.html
  FAIL TestDriver actions: two touch points with one moving one pause - assert_array_equals: lengths differ, expected array ["pointerdown", "pointerdown", "pointermove", "pointerup", "pointerup"] length 5, got ["pointerdown", "pointerdown", "pointermove", "pointerup"] length 4
    at Test.<anonymous> (http://web-platform.test:8000/infrastructure/testdriver/actions/multiTouchPointsReleaseSecondPoint.html:52:7)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:2044:25)
    at http://web-platform.test:8000/resources/testharness.js:2085:32
```

We'll need to add an infrastructure expectation for this.

cc @LanWei22

**Comment by stephenmcgruer** [comment]
See https://github.com/web-platform-tests/wpt/issues/20838 for a previous case where this test was failing (over a year ago now)

**Comment by stephenmcgruer** [comment]
It's possible something is flaky here; my attempt to add metadata failed because the test passed rather than failed! https://github.com/web-platform-tests/wpt/pull/27201

**Comment by stephenmcgruer** [comment]
This is being marked flaky in https://github.com/web-platform-tests/wpt/pull/27278#pullrequestreview-573716376 so lowering the priority and assigning LanWei22 to investigate. This test no longer passes reliably on any browser!
