### ISSUE TITLE
TypeError: Cannot read property 'index' of null from testharness.js

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#27299]
934077ad8594041ef09a19181434f32c10c34d20 has caused a regression in `native-io/rename_sync_failure_handling.tentative.https.any.worker.html`:

```
$ ./wpt run --channel=dev chrome native-io/rename_sync_failure_handling.tentative.https.any.worker.html
Running 1 tests in web-platform-tests

  ▶ ERROR [expected OK] /native-io/rename_sync_failure_handling.tentative.https.any.worker.html
  │   → Uncaught TypeError: Cannot read property 'index' of null
  │ 
  │ TypeError: Cannot read property 'index' of null
  │     at RemoteContext.remote_done (https://web-platform.test:8443/resources/testharness.js:2632:50)
  └     at Worker.RemoteContext.message_handler (https://web-platform.test:8443/resources/testharness.js:2558:62)

  [1/1] No tests running.
```

It looks like this test has an assert in its `setup` method, and the code can't handle that:

```
        for (let assert of data.asserts) {
            var record = new AssertRecord();
            record.assert_name = assert.assert_name;
            record.args = assert.args;
            record.test = this.tests[assert.test.index];  <---- this line
            record.status = assert.status;
            record.stack = assert.stack;
            tests.asserts_run.push(record);
        }
```
cc @jgraham

**Comment by jgraham** [comment]
This was fixed I believe.

**Comment by stephenmcgruer** [comment]
It was, in https://github.com/web-platform-tests/wpt/pull/27308 . Which had the magical 'fixes' text, but GitHub didn't link this and close it? Interesting...

Thanks for cleaning up :)
