### ISSUE TITLE
OpenSSLEnviornment.check_key_cert throws a TypeError on Windows Python 3

### ISSUE THREAD

**Issue by donny-dont** [web-platform-tests/wpt#27879]
When running `wpt.py serve` within WebKit's `run-webkit-tests` harness on Windows with Python 3.9.x I get the following error message.

```
PS C:\webkit> python C:\webkit\LayoutTests\imported\w3c\web-platform-tests\wpt.py serve --config C:\webkit\LayoutTests\imported\w3c\web-platform-tests\config.json
WARNING:web-platform-tests:bind_hostname in config is deprecated; use bind_address instead
WARNING:web-platform-tests:bind_hostname in config is deprecated; use bind_address instead
DEBUG:web-platform-tests:b'notAfter=Apr  2 17:19:06 2021 GMT\r\n'
Traceback (most recent call last):
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\wpt.py", line 7, in <module>
    exec(compile(open("wpt", "r").read(), "wpt", 'exec'))
  File "wpt", line 5, in <module>
    wpt.main()
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wpt\wpt.py", line 169, in main
    rv = script(*args, **kwargs)
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\serve\serve.py", line 1078, in run
    with build_config(os.path.join(repo_root, "config.json"),
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wptserve\wptserve\config.py", line 270, in __enter__
    data[key] = getattr(self, prefix + key)(data)
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wptserve\wptserve\config.py", line 346, in _get_ssl_config
    key_path, cert_path = self._ssl_env.host_cert_path(data["domains_set"])
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wptserve\wptserve\sslutils\openssl.py", line 376, in host_cert_path
    key_cert = self._load_host_cert(hosts)
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wptserve\wptserve\sslutils\openssl.py", line 393, in _load_host_cert
    if self.check_key_cert(key_path, cert_path, hosts):
  File "C:\webkit\LayoutTests\imported\w3c\web-platform-tests\tools\wptserve\wptserve\sslutils\openssl.py", line 318, in check_key_cert
    end_date_str = openssl("x509",
TypeError: a bytes-like object is required, not 'str'
```

**Comment by stephenmcgruer** [comment]
cc @gsnedders as this is within the `run-webkit-tests` hardness (and I'm not sure how up-to-date the copy of wptserve is there). eaa285dde18846df518b8081b0d1f86997e06580 may be related

**Comment by donny-dont** [comment]
@stephenmcgruer I opened a PR with a change that gets things running on Windows with Python 3. Feel free to propose another fix.

@gsnedders I actually have the latest `wpt/tools` in my local webkit directory. The issue and the fix are the same for the current code in webkit as well as the current upstream code.
