### ISSUE TITLE
progress-events-response-data-gzip.htm is broken on Python3

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#27917]
See http://wpt.live/xhr/progress-events-response-data-gzip.htm . The request to `http://wpt.live/xhr/resources/image.gif?pipe=gzip|trickle(45000:d1:r2)` gives back a 500. The test is fine with this and still passes, but it isn't testing what it's supposed to test.

(And, the test fails on jsdom, where a single-chunk XHR dispatches two `progress` events, per spec... That's a separate issue.)

**Comment by stephenmcgruer** [comment]
Thanks for the report!

Error message from the network request:

```
string argument expected, got 'bytes'
Traceback (most recent call last):
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/server.py", line 283, in finish_handling handler(request, response)
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/handlers.py", line 229, in __call__
response = wrap_pipeline(path, request, response)
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/handlers.py", line 165, in wrap_pipeline
response = Pipeline(pipe_string)(request, response)
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/pipes.py", line 40, in __call__
response = func(request, response, *args)
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/pipes.py", line 133, in inner
return f(request, response, *arg_values)
File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/pipes.py", line 552, in gzip
with gzip_module.GzipFile(fileobj=out, mode="w") as f:
File "/home/smcgruer/miniconda3/lib/python3.8/gzip.py", line 204, in __init__
self._write_gzip_header(compresslevel)
File "/home/smcgruer/miniconda3/lib/python3.8/gzip.py", line 232, in _write_gzip_header
self.fileobj.write(b'\037\213')             # magic header
TypeError: string argument expected, got 'bytes'↵"
```
