### ISSUE TITLE
wpt serve-wave command doesn't work

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#29024]
Running `./wpt serve-wave` at commit dd606b49f35ae72db23084be111714f532a88a6d for me produces this error:
```
INFO:manifest:Updating manifest
Traceback (most recent call last):
  File "./wpt", line 11, in <module>
    wpt.main()
  File "/Users/foolip/wpt/wpt/tools/wpt/wpt.py", line 169, in main
    rv = script(*args, **kwargs)
  File "/Users/foolip/wpt/wpt/tools/serve/wave.py", line 90, in run
    serve.run(config_cls=ConfigBuilder,
  File "/Users/foolip/wpt/wpt/tools/serve/serve.py", line 1111, in run
    check_subdomains(config, routes, mp_context)
  File "/Users/foolip/wpt/wpt/tools/serve/serve.py", line 573, in check_subdomains
    wrapper.start(start_http_server, host, port, paths, routes,
  File "/Users/foolip/wpt/wpt/tools/serve/serve.py", line 513, in start
    self.proc.start()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_route_builder_func.<locals>.get_route_builder.<locals>.WaveHandler'
```

`WaveHandler` is an inline class here:
https://github.com/web-platform-tests/wpt/blob/1942e78bc41a6fdb5a7fa9d932bd95fd75051a50/tools/serve/wave.py#L34-L36

I'm not sure what's wrong, but think it has to do with changes in Python's multiprocess code in Python 3, where everything has to be picklable.

@louaybassbouss are you able to look into this?

**Comment by foolip** [comment]
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method says "it should be protected inside the if __name__ == '__main__' clause of the main module which would require putting it in the root `wpt` script. I don't know why the documentation says that, and *guess* that calling it from a method called from that clause is fine, but 🤷
