### ISSUE TITLE
Edge Dev runs on Azure Pipelines failing due to edgedriver not being found

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#29520]
Starting on [June 25](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=67071&view=logs&j=2b376673-b6b7-55d3-67e2-e8305abf5c1e&t=74a04147-a139-56ed-eca1-af09b5915baa), Edge Dev runs on Azure Pipelines have been failing fast, with an error like this:
```
 0:00.11 INFO Downloading msedgedriver
 0:00.25 INFO Downloading MSEdgeDriver from https://msedgedriver.azureedge.net/93.0.926.1/edgedriver_win32.zip
Traceback (most recent call last):
  File "C:\Agent\_work\1\s\wpt", line 11, in <module>
    wpt.main()
  File "C:\Agent\_work\1\s\tools\wpt\wpt.py", line 179, in main
    rv = script(*args, **kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 846, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 814, in setup_wptrunner
    setup_cls.setup(kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 183, in setup
    self.setup_kwargs(kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 549, in setup_kwargs
    webdriver_binary = self.browser.install_webdriver(
  File "C:\Agent\_work\1\s\tools\wpt\browser.py", line 1135, in install_webdriver
    unzip(get(url).raw, dest)
  File "C:\Agent\_work\1\s\tools\wpt\utils.py", line 69, in get
    resp.raise_for_status()
  File "C:\Agent\_work\1\s\_venv3\Lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://msedgedriver.azureedge.net/93.0.926.1/edgedriver_win32.zip
##[error]Cmd.exe exited with code '1'.
Finishing: Run tests (Edge Dev)
```

@thejohnjansen @mustjab can either of you take a look at this?

@Ms2ger asked about this on the Matrix channel (new, documented at https://web-platform-tests.org/)

**Comment by foolip** [comment]
This is the code path where things go wrong:
https://github.com/web-platform-tests/wpt/blob/7b0ebaccc62b566a1965396e5be7bb2bc06f841f/tools/wpt/browser.py#L1102-L1138

**Comment by mustjab** [comment]
Thanks for letting us know. The issue appears to be due to us picking up Linux only builds and we're looking for a way to filter them out.

**Comment by mustjab** [comment]
Yes, that's the fix that Brandon is working on to make driver detection OS aware.

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/29522.
