### ISSUE TITLE
wptrunner crashed when running all tests against webview

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#32506]
Log as below:

```
ERROR Unsupported test type print-reftest for product android_webview
mozlog.structuredlog: Failure calling log handler:
Traceback (most recent call last):
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/structuredlog.py", line 294, in _handle_log
    handler(data)
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/handlers/base.py", line 73, in __call__
    formatted = self.formatter(data)
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/handlers/base.py", line 41, in __call__
    return self.inner(item)
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/reader.py", line 74, in __call__
    return handler(data)
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/formatters/grouping.py", line 361, in suite_end
    results = self.get_lines_for_known_intermittents(
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/808e98/lib/python3.8/site-packages/mozlog/formatters/grouping.py", line 196, in get_lines_for_known_intermittents
    data["expected"],
KeyError: 'expected'

Command returned exit code 1
```

Command executed:

```
wpt --no-fail-on-unexpected-pass --venv=/b/s/w/ir --skip-venv-setup run --tests=/b/s/w/ir/third_party/blink/web_tests/external/wpt --webdriver-binary clang_x64/chromedriver --symbols-path /b/s/w/ir/out/Release --stackwalk-binary /b/s/w/ir/build/android/tombstones.py --headless --no-pause-after-test --no-capture-stdio --no-manifest-download --binary-arg=--enable-blink-features=MojoJS,MojoJSTest --binary-arg=--enable-blink-test-features --binary-arg=--disable-field-trial-config --enable-mojojs --mojojs-path=/b/s/w/ir/out/Release/gen --binary-arg=--enable-features=DownloadService<DownloadServiceStudy --binary-arg=--force-fieldtrials=DownloadServiceStudy/Enabled --binary-arg=--force-fieldtrial-params=DownloadServiceStudy.Enabled:start_up_delay_ms/0 --device-serial emulator-5554 --metadata /b/s/w/ityy72ui77/tmp89a33mgf/metadata_dir --log-wptreport /b/s/w/iowbvgtbcc/wpt_reports_android_webview_05.json --package-name com.google.android.webview_shell android_webview --log-chromium /b/s/w/iowbvgtbcc/output.json --total-chunks=25 --this-chunk=6 --chunk-type=hash
```

**Comment by gsnedders** [comment]
cc @jgraham

**Comment by WeizhongX** [comment]
This should have been fixed by https://github.com/web-platform-tests/wpt/pull/32838

Close for now.
