### ISSUE TITLE
wptrunner crashed when parsing metadata

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#32708]
Stack trace as below. In stead of crash, I think we should skip that metadata, and allow the single test to fail.

```
Traceback (most recent call last):
  File "/b/s/w/ir/third_party/wpt_tools/wpt/wpt", line 11, in <module>
    wpt.main()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/wpt.py", line 215, in main
    rv = script(*args, **kwargs)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/run.py", line 866, in run
    rv = run_single(venv, **wptrunner_kwargs) > 0
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/run.py", line 873, in run_single
    return wptrunner.start(**kwargs)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 465, in start
    rv = not run_tests(**kwargs)[0] or logged_critical.has_log
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 319, in run_tests
    run_info, test_loader = get_loader(test_paths,
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 81, in get_loader
    test_loader = testloader.TestLoader(test_manifests,
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/testloader.py", line 255, in __init__
    self._load_tests()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/testloader.py", line 318, in _load_tests
    for test_path, test_type, test in self.iter_tests():
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/testloader.py", line 309, in iter_tests
    inherit_metadata, test_metadata = self.load_metadata(manifest_file, metadata_path, test_path)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/testloader.py", line 288, in load_metadata
    test_metadata = manifestexpected.get_manifest(
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/manifestexpected.py", line 517, in get_manifest
    return static.compile(f,
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/backends/static.py", line 97, in compile
    return compile_ast(parse(stream),
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 786, in parse
    return p.parse(stream)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 537, in parse
    self.manifest()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 561, in manifest
    self.data_block()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 582, in data_block
    self.data_block()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 579, in data_block
    self.expect(token_types.paren, "]")
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 558, in expect
    self.consume()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 547, in consume
    self.token = next(self.token_generator)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 100, in tokenize
    tokens = self.state()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptmanifest/parser.py", line 367, in line_end_state
    raise ParseError(self.filename, self.line_number, "Junk before EOL %s" % c)
wptrunner.wptmanifest.parser.ParseError: Junk before EOL c: /b/s/w/ir/out/Release/wpt_expectations_metadata/input-events/input-events-get-target-ranges-forwarddelete.tentative.html.ini line 4
Command returned exit code 1
Traceback (most recent call last):
  File "/b/s/w/ir/testing/scripts/common.py", line 478, in run_test
    self.do_post_test_run_tasks()
  File "/b/s/w/ir/testing/scripts/wpt_common.py", line 98, in do_post_test_run_tasks
    self.process_wptrunner_output(
  File "/b/s/w/ir/testing/scripts/wpt_common.py", line 156, in process_wptrunner_output
    output_json = json.load(f)
  File "/b/s/w/ir/.task_template_packages/cpython3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/b/s/w/ir/.task_template_packages/cpython3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/b/s/w/ir/.task_template_packages/cpython3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/b/s/w/ir/.task_template_packages/cpython3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
result_adapter: did not recognize as json test result format: "" not map[string]json.RawMessage: unexpected end of JSON input
```

**Comment by WeizhongX** [comment]
close as won't fix
