### ISSUE TITLE
show-picker-cross-origin-iframe.html is flaky (PASS or ERROR) in Chrome

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#32925]
This test is part of Interop 2022 and flips between passing and erroring:
https://wpt.fyi/results/html/semantics/forms/the-input-element/show-picker-cross-origin-iframe.html?run_id=5706281338798080&run_id=5094969516752896

The error is:
```
ERROR message: target frame detached
  (Session info: chrome=100.0.4892.0)
Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 406, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 496, in do_testharness
    result = protocol.base.execute_script(
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 50, in execute_script
    return method(script)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 791, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 659, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 623, in send_command
    raise err
webdriver.error.WebDriverException: target frame detached (404): target frame detached
  (Session info: chrome=100.0.4892.0)

Remote-end stacktrace:

#0 0x5624e86681a9 <unknown>
#1 0x5624e8605333 <unknown>
#2 0x5624e8329377 <unknown>
#3 0x5624e83161be <unknown>
#4 0x5624e8315140 <unknown>
#5 0x5624e831562b <unknown>
#6 0x5624e8315585 <unknown>
#7 0x5624e831c83f <unknown>
#8 0x5624e831caf2 <unknown>
#9 0x5624e8316930 <unknown>
#10 0x5624e8317054 <unknown>
#11 0x5624e8316dc2 <unknown>
#12 0x5624e831630c <unknown>
#13 0x5624e8315140 <unknown>
#14 0x5624e831562b <unknown>
#15 0x5624e8333369 <unknown>
#16 0x5624e832bf43 <unknown>
#17 0x5624e832bbb6 <unknown>
#18 0x5624e832c374 <unknown>
#19 0x5624e832c677 <unknown>
#20 0x5624e832c9e8 <unknown>
#21 0x5624e832d01b <unknown>
#22 0x5624e838fbe0 <unknown>
#23 0x5624e837c152 <unknown>
#24 0x5624e838ed9c <unknown>
#25 0x5624e837c043 <unknown>
#26 0x5624e835254b <unknown>
#27 0x5624e8353715 <unknown>
#28 0x5624e8632460 <unknown>
#29 0x5624e8643d79 <unknown>
#30 0x5624e8643a9c <unknown>
#31 0x5624e8644272 <unknown>
#32 0x5624e86338ab <unknown>
#33 0x5624e86444de <unknown>
#34 0x5624e86257ed <unknown>
#35 0x5624e865ae68 <unknown>
#36 0x5624e865aff2 <unknown>
#37 0x5624e867459e <unknown>
#38 0x7f312108b609 <unknown>
#39 0x7f3120b31293 <unknown>
```

The test was renamed in https://github.com/web-platform-tests/wpt/pull/32031 and the error has been happening since at least Dec 26:
https://wpt.fyi/results/html/semantics/forms/the-input-element/show-picker-cross-origin-iframe.html?run_id=5741165811859456

**Comment by foolip** [comment]
@josepharhar can you help investigate this? This failure might be the difference between Chrome getting an Interop 2022 score of 71 or 72, or at least it's part of the cause for a decrease, together with https://github.com/web-platform-tests/wpt-metadata/pull/2519.

**Comment by josepharhar** [comment]
Sorry for the delay, looking at this now: https://bugs.chromium.org/p/chromium/issues/detail?id=1316643

**Comment by josepharhar** [comment]
Looks to me like the test is passing now: https://wpt.fyi/results/html/semantics/forms/the-input-element/show-picker-cross-origin-iframe.html
