### ISSUE TITLE
Python 3.6 CI "ModuleNotFoundError: No module named 'distutils.cmd'"

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt#33776]
Many recent CI runs on Python 3.6 are seeing this error unrelated to their change

```
ERROR: could not install deps [-r/home/test/web-platform-tests/tools/requirements_flake8.txt]; v = InvocationError('/home/test/web-platform-tests/tools/.tox/py36-flake8/bin/python -m pip install -r/home/test/web-platform-tests/tools/requirements_flake8.txt', 1)
py36-mypy create: /home/test/web-platform-tests/tools/.tox/py36-mypy
py36-mypy installdeps: -r/home/test/web-platform-tests/tools/requirements_mypy.txt
ERROR: invocation failed (exit code 1), logfile: /home/test/web-platform-tests/tools/.tox/py36-mypy/log/py36-mypy-1.log
================================== log start ===================================
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/home/test/web-platform-tests/tools/.tox/py36-mypy/lib/python3.6/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

This likely need to be investigated, as it could continue blocking PRs.

**Comment by foolip** [comment]
@DanielRyanSmith what is the earliest PR you can find where this happens? Are there any suspicious changes that landed soon before that, like changes to Python setup and dependencies?

**Comment by DanielRyanSmith** [comment]
I'm having trouble finding any instance of this type of failure later than 24-48 hours ago. Although this might be caused by a dependency change, I think recent vendored dependency changes are unlikely to be the cause.

**Comment by foolip** [comment]
I tried to bisect this in a webplatformtests/wpt:0.48 container, and can repro on master, but also on commit 5746f470ebc1fa2df9edad147a468f6d5f4c1f68 from March 8, so I don't think this is a regression in the wpt repo.

Installing python3.6-distutils fixes the problem, so probably something in the python3.6 or python3.6-dev package changed.
