### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.packaging' after #33706

### ISSUE THREAD

**Issue by flackr** [web-platform-tests/wpt#33873]
As of PR #33706, I seem to run into some errors trying to run `./wpt run`, e.g.

```
flackr@flackr-l:~/projects/wpt$ ./wpt run firefox
Traceback (most recent call last):
  File "/usr/local/google/home/flackr/projects/wpt/_venv3/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/google/home/flackr/projects/wpt/_venv3/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/google/home/flackr/projects/wpt/_venv3/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/google/home/flackr/projects/wpt/_venv3/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/google/home/flackr/projects/wpt/_venv3/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._vendor.packaging.utils import canonicalize_name
ModuleNotFoundError: No module named 'pip._vendor.packaging'
CRITICAL:tools.wpt.utils:('/usr/local/google/home/flackr/projects/wpt/_venv3/bin/pip3', 'install', '--prefer-binary', '-r', '/usr/local/google/home/flackr/projects/wpt/tools/wpt/../webtransport/requirements.txt') exited with return code 1
CRITICAL:tools.wpt.utils:b''
Traceback (most recent call last):
  File "/usr/local/google/home/flackr/projects/wpt/./wpt", line 10, in <module>
    wpt.main()
  File "/usr/local/google/home/flackr/projects/wpt/tools/wpt/wpt.py", line 211, in main
    install_command_flag_requirements(venv, kwargs, requirements)
  File "/usr/local/google/home/flackr/projects/wpt/tools/wpt/wpt.py", line 166, in install_command_flag_requirements
    venv.install_requirements(path)
  File "/usr/local/google/home/flackr/projects/wpt/tools/wpt/virtualenv.py", line 133, in install_requirements
    call(
  File "/usr/local/google/home/flackr/projects/wpt/tools/wpt/utils.py", line 25, in call
    return subprocess.check_output(args).decode('utf8')
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/usr/local/google/home/flackr/projects/wpt/_venv3/bin/pip3', 'install', '--prefer-binary', '-r', '/usr/local/google/home/flackr/projects/wpt/tools/wpt/../webtransport/requirements.txt')' returned non-zero exit status 1.
```

I believe I have followed all of the instructions at https://web-platform-tests.org/running-tests/from-local-system.html#linux-setup

**Comment by foolip** [comment]
@flackr this looks a bit similar to https://github.com/web-platform-tests/wpt/issues/33776 but with a different error. Can you try installing python3.9-distutils and see if that fixes the problem? If it doesn't, it's probably some other package...

**Comment by DanielRyanSmith** [comment]
Hey @flackr, I'm not able to reproduce this on the `master` branch code at the moment using `./wpt run firefox`, but it's likely related to the vendored dependency `packaging` being updated recently. I would try this:
- Make sure your working branch is up to date
- delete your `_venv3` folder located in the repo's root directory and it will be set up again from scratch on the next invocation of `./wpt run`

I'm hoping this hard reset fixes the issue. Let me know your findings!

**Comment by flackr** [comment]
Yes, deleting `_venv` fixed the issue on the current checkout and after updating my branch to the latest.

Would it make sense to suggest this to the user if `install_command_flag_requirements` throws an error?
