### ISSUE TITLE
WPT fails to start with chrome

### ISSUE THREAD

**Issue by saschanaz** [web-platform-tests/wpt#34407]
```
> python wpt run --pause-after-test --no-headless chrome html/semantics/forms/event-propagate-disabled.html
Download and install chromedriver [Y/n]? y
Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\wpt", line 10, in <module>
    wpt.main()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wpt\wpt.py", line 220, in main
    rv = script(*args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wpt\run.py", line 834, in run
    rv = run_single(venv, **wptrunner_kwargs) > 0
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wpt\run.py", line 841, in run_single
    return wptrunner.start(**kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\wptrunner.py", line 471, in start
    rv = not run_tests(**kwargs)[0] or logged_critical.has_log
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\wptrunner.py", line 371, in run_tests
    test_environment.ensure_started()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\environment.py", line 271, in ensure_started
    raise OSError("Servers failed to start: %s" %
OSError: Servers failed to start: 127.0.0.1:11000
```

It works well with Firefox, no idea why it fails to start. Windows 11, Python 3.10, Chrome version 102.0.5005.115.

**Comment by saschanaz** [comment]
Dupe of #34443.
