### ISSUE TITLE
Safari Technology Preview downloads are failing after page update

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt#34875]
[Pipeline run](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=84583&view=logs&jobId=d41515ed-d71e-5e8d-de88-940c2a934d56&j=42513d51-f539-5b97-080a-60c327907e2e&t=0831e07d-b569-54b4-d687-33f1efddc82e)

```sh
Traceback (most recent call last):
  File "/Users/runner/work/1/s/./wpt", line 10, in <module>
    wpt.main()
  File "/Users/runner/work/1/s/tools/wpt/wpt.py", line 220, in main
    rv = script(*args, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/install.py", line 89, in run
    install(browser, kwargs["component"], destination, channel, logger=logger,
  File "/Users/runner/work/1/s/tools/wpt/install.py", line 109, in install
    path = getattr(browser_cls(logger), method)(dest=destination, channel=channel, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/browser.py", line 1612, in download
    image_path = self._download_image(stp_downloads, tmpdir, system_version)
  File "/Users/runner/work/1/s/tools/wpt/browser.py", line 1530, in _download_image
    raise ValueError(f"no download for {system_version}")
ValueError: no download for 12.4

```

Similar to #34752 

Looks like the page has changed.
Here's a diff between the [file created for testing ](https://github.com/web-platform-tests/wpt/blob/master/tools/wpt/tests/safari_downloads_page_stp_section.html) and now

```diff
 <div class="column large-6 medium-12 small-12">
     <div class="callout">
-        <figure class="app-icon large-icon safari-preview-icon" aria-hidden="true" data-hires-status="pending"></figure>
+        <figure class="app-icon large-icon safari-preview-icon" aria-hidden="true"></figure>
         <h4>Safari Technology Preview</h4>
         <p class="margin-bottom-small">Get a sneak peek at upcoming web technologies in macOS and iOS with <a href="/safari/technology-preview/" class="nowrap">Safari Technology Preview</a> and experiment with these technologies in your websites and extensions.</p>
         <ul class="links small">
-            <li class="dmg" data-hires-status="pending"><a class="inline" href="https://secure-appldnld.apple.com/STP/012-38225-20220706-237860CD-5766-4F53-AAC7-1CE26023A959/SafariTechnologyPreview.dmg">Safari Technology Preview<br>for macOS&nbsp;Ventura</a><br><span class="smaller lighter nowrap nowrap-small">Requires macOS&nbsp;13 beta&nbsp;3 or later.</span></li>
-            <li class="dmg margin-top-small" data-hires-status="pending"><a class="inline" href="https://secure-appldnld.apple.com/STP/012-32918-20220629-B3452905-0138-4CA9-A4E6-334B63585653/SafariTechnologyPreview.dmg">Safari Technology Preview<br>for macOS&nbsp;Monterey</a><br><span class="smaller lighter">Requires macOS&nbsp;12.3 or later.</span></li>
-            <li class="document margin-top-small" data-hires-status="pending"><a href="/safari/technology-preview/release-notes/">Release Notes</a></li>
+            <li class="dmg"><a class="inline" href="https://secure-appldnld.apple.com/STP/012-38225-20220706-237860CD-5766-4F53-AAC7-1CE26023A959/SafariTechnologyPreview.dmg">Safari Technology Preview 148<br />for macOS&nbsp;Ventura</a><br /><span class="smaller lighter nowrap nowrap-small">Requires macOS&nbsp;13 beta&nbsp;3 or later.</span></li>
+            <li class="dmg margin-top-small"><a class="inline" href="https://secure-appldnld.apple.com/STP/012-38074-20220715-4851625A-8AC7-4155-84C0-AEB4B88F08FE/SafariTechnologyPreview.dmg">Safari Technology Preview 149<br />for macOS&nbsp;Monterey</a><br /><span class="smaller lighter">Requires macOS&nbsp;12.3 or later.</span></li>
+            <li class="document margin-top-small"><a href="/safari/technology-preview/release-notes/">Release Notes</a></li>
         </ul>
         <div class="row gutter text-left">
             <div class="column">
                 <p class="sosumi no-margin-bottom margin-top-small">Release</p>
-                <p class="smaller lighter no-margin">148</p>
+                <p class="smaller lighter no-margin">149</p>
             </div>
             <div class="column">
                 <p class="sosumi no-margin-bottom margin-top-small">Posted</p>
-                <p class="smaller lighter no-margin">June 29, 2022</p>
+                <p class="smaller lighter no-margin">July 14, 2022</p>
             </div>
         </div>
     </div>
```

@gsnedders

**Comment by jcscottiii** [comment]
I can make a PR for this @gsnedders 
I see that there is now a number there:

Previously:
`Safari Technology Preview<br>for macOS&nbsp;Ventura`

Now:
`Safari Technology Preview 148<br />for macOS&nbsp;Ventura`
