### ISSUE TITLE
Error running wpt run (ERROR: Failed building wheel for psutil)

### ISSUE THREAD

**Issue by flackr** [web-platform-tests/wpt#36053]
Following the steps for [running tests locally on macOS](https://web-platform-tests.org/running-tests/from-local-system.html#macos-setup) failed when I tried to run a test:

```
flackr-macbookpro:wpt flackr$ ./wpt run --channel=preview safari /pointerevents/pointerevent_movementxy.html?mouse
  error: subprocess-exited-with-error
  
  × Building wheel for psutil (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_pswindows.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_common.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_psosx.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_psbsd.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_psaix.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_pslinux.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_compat.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_psposix.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      copying psutil/_pssunos.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil
      creating build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_contracts.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_connections.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/runner.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_unicode.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_misc.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_posix.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_linux.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_sunos.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_aix.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_process.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_bsd.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_system.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_osx.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_memleaks.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_windows.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/__main__.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/foo.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      copying psutil/tests/test_testutils.py -> build/lib.macosx-10.9-universal2-cpython-39/psutil/tests
      running build_ext
      building 'psutil._psutil_osx' extension
      creating build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/psutil
      creating build/temp.macosx-10.9-universal2-cpython-39/psutil/arch
      creating build/temp.macosx-10.9-universal2-cpython-39/psutil/arch/osx
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=591 -DPSUTIL_OSX=1 -I/Users/flackr/projects/wpt/_venv3/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c psutil/_psutil_common.c -o build/temp.macosx-10.9-universal2-cpython-39/psutil/_psutil_common.o
      psutil/_psutil_common.c:9:10: fatal error: 'Python.h' file not found
      #include <Python.h>
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/Users/flackr/projects/wpt/./wpt", line 10, in <module>
    wpt.main()
  File "/Users/flackr/projects/wpt/tools/wpt/wpt.py", line 220, in main
    rv = script(*args, **kwargs)
  File "/Users/flackr/projects/wpt/tools/wpt/run.py", line 851, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "/Users/flackr/projects/wpt/tools/wpt/run.py", line 782, in setup_wptrunner
    setup_cls.install_requirements()
  File "/Users/flackr/projects/wpt/tools/wpt/run.py", line 185, in install_requirements
    self.venv.install_requirements(os.path.join(
  File "/Users/flackr/projects/wpt/tools/wpt/virtualenv.py", line 135, in install_requirements
    call(
  File "/Users/flackr/projects/wpt/tools/wpt/utils.py", line 27, in call
    return subprocess.check_output(args).decode('utf8')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/Users/flackr/projects/wpt/_venv3/bin/pip3', 'install', '--prefer-binary', '-r', '/Users/flackr/projects/wpt/tools/wptrunner/requirements_safari.txt')' returned non-zero exit status 1.
```

Possibly related is that I only have python3 on my system so for the beginning steps I used:

```
python3 -m ensurepip --user
export PATH="$PATH:$HOME/Library/Python/3.9/bin"
pip3 install --user virtualenv
```

**Comment by zcorpan** [comment]
I got this error as well.

**Comment by jgraham** [comment]
I guess you're missing some Python header files? I don't have a mac so can't really debug this. Are you using system Python or one installed through some other means like homebrew etc.? I'm a bit surprised that there isn't a binary psutil found, but maybe we're stuck on an older version?

**Comment by zcorpan** [comment]
I installed XCode and now there's no error.

I don't have homebrew. Don't remember if I tried installing Python somehow, but `python3` gives this message which I think indicates it's system Python
```
% python3
Python 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
