### ISSUE TITLE
local variable 'clean' referenced before assignment

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#36109]
When run "/wpt run --log-mach - --yes --manifest /home/test/meta/MANIFEST.json --metadata infrastructure/metadata/ --install-fonts --install-webdriver '--binary=~/build/firefox/firefox' firefox infrastructure/", get error as below.

Link to the log: https://community-tc.services.mozilla.com/tasks/VwqT4NQXQuiKqKoxVq8iqg/runs/0/logs/public/logs/live.log#L565

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 346 checks (200 subtests, 146 tests)
Expected results: 345
Skipped: 1 tests
Unexpected results: 0
OK
 2:43.58 INFO STDERR: TestRunnerManager-print-reftest-0
 2:43.59 INFO STDERR: :
 2:43.59 INFO STDERR: Traceback (most recent call last):
 2:43.59 INFO STDERR:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: self.run()
 2:43.59 INFO STDERR:   File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 392, in run
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: self.teardown()
 2:43.59 INFO STDERR:   File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 797, in teardown
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: self.browser.browser.cleanup()
 2:43.59 INFO STDERR:   File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/browsers/firefox.py", line 807, in cleanup
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: self.instance_manager.teardown(force)
 2:43.59 INFO STDERR:   File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/browsers/firefox.py", line 365, in teardown
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: instance.stop(force)
 2:43.59 INFO STDERR:   File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/browsers/firefox.py", line 447, in stop
 2:43.59 INFO STDERR:     
 2:43.59 INFO STDERR: self.output_handler.after_process_stop(clean_shutdown=clean)
 2:43.59 INFO STDERR: UnboundLocalError
 2:43.59 INFO STDERR: : 
 2:43.59 INFO STDERR: local variable 'clean' referenced before assignment

**Comment by WeizhongX** [comment]
@jgraham fyi
