### ISSUE TITLE
Exception when reading from web socket connection (I/O operation on closed file)

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#38426]
Exception in thread Thread-223:
Traceback (most recent call last):
  File "/b/s/w/ir/.task_template_packages/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/b/s/w/ir/.task_template_packages/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptserve/wptserve/server.py", line 544, in _stream_ws_sub_thread
    dispatcher.transfer_data(request)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/dispatch.py", line 287, in transfer_data
    transfer_data_(request)
  File "<string>", line 14, in web_socket_transfer_data
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 806, in receive_message
    frame = self._receive_frame_as_frame_object()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 514, in _receive_frame_as_frame_object
    opcode, unmasked_bytes, fin, rsv1, rsv2, rsv3 = self._receive_frame()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 508, in _receive_frame
    return parse_frame(receive_bytes=_receive_bytes,
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 272, in parse_frame
    raw_payload_bytes = receive_bytes(payload_length)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 506, in _receive_bytes
    return self.receive_bytes(length)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 475, in receive_bytes
    new_read_bytes = self._read(length)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/third_party/pywebsocket3/mod_pywebsocket/stream.py", line 440, in _read
    read_bytes = self._request.connection.read(length)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptserve/wptserve/server.py", line 905, in read
    return self._request_handler.rfile.read(length)
ValueError: web_socket_transfer_data raised exception for /receive-backpressure: I/O operation on closed file

**Comment by WeizhongX** [comment]
Hi @ricea , I see you made change to websockets/handlers/receive-backpressure_wsh.py last time. Do you might have any idea on this?
