### ISSUE TITLE
No Edge runs since 7 Jul 2023

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#41062]
c.f. https://wpt.fyi/runs?label=master&max-count=100&product=edge

All the Edge jobs seem to be timing out after 3h, which is also a great waste of our capacity on Azure Pipelines.

We seem to end up in some state like:

```
2023-07-17T02:16:36.7936699Z  0:26.05 ERROR Traceback (most recent call last):
2023-07-17T02:16:36.7938226Z   File "D:\a\1\s\tools\wptrunner\wptrunner\testrunner.py", line 210, in init
2023-07-17T02:16:36.7939108Z     self.browser.start(group_metadata=group_metadata, **self.browser_settings)
2023-07-17T02:16:36.7939613Z   File "D:\a\1\s\tools\wptrunner\wptrunner\browsers\base.py", line 318, in start
2023-07-17T02:16:36.7939981Z     self._run_server(group_metadata, **kwargs)
2023-07-17T02:16:36.7940308Z   File "D:\a\1\s\tools\wptrunner\wptrunner\browsers\base.py", line 341, in _run_server
2023-07-17T02:16:36.7940631Z     self._proc.run()
2023-07-17T02:16:36.7940980Z   File "d:\a\1\s\_venv3\lib\site-packages\mozprocess\processhandler.py", line 946, in run
2023-07-17T02:16:36.7941300Z     self.proc = self.Process([self.cmd] + self.args, **args)
2023-07-17T02:16:36.7941576Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-17T02:16:36.7942222Z   File "d:\a\1\s\_venv3\lib\site-packages\mozprocess\processhandler.py", line 160, in __init__
2023-07-17T02:16:36.7943006Z     subprocess.Popen.__init__(self, args, **kwargs)
2023-07-17T02:16:36.7943581Z   File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\subprocess.py", line 1026, in __init__
2023-07-17T02:16:36.7943972Z     self._execute_child(args, executable, preexec_fn, close_fds,
2023-07-17T02:16:36.7944366Z   File "d:\a\1\s\_venv3\lib\site-packages\mozprocess\processhandler.py", line 295, in _execute_child
2023-07-17T02:16:36.7945007Z     (
2023-07-17T02:16:36.7945263Z ValueError: too many values to unpack (expected 22)
2023-07-17T02:16:36.7945397Z 
2023-07-17T02:16:36.7945693Z  0:26.05 INFO STDERR: Exception ignored in: 
2023-07-17T02:16:36.8152684Z  0:26.07 INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x0000018909317060>
2023-07-17T02:16:36.8159486Z  0:26.07 INFO STDERR: Traceback (most recent call last):
2023-07-17T02:16:36.8162248Z  0:26.07 INFO STDERR:   File "d:\a\1\s\_venv3\lib\site-packages\mozprocess\processhandler.py", line 191, in __del__
2023-07-17T02:16:36.8163364Z  0:26.07 INFO STDERR:     
2023-07-17T02:16:36.8166308Z  0:26.07 INFO STDERR: if handle or self._job or self._io_port:
```

We also seem to never exit from wptrunner until the job is terminated by Azure Pipelines:

```
2023-07-17T02:16:37.4841027Z  0:26.74 INFO queue closed
2023-07-17T02:16:37.4842395Z  0:26.74 WARNING All requested tests were skipped
2023-07-17T05:11:04.3530732Z Terminate batch job (Y/N)? 
2023-07-17T05:11:04.4090685Z ^C
2023-07-17T05:11:04.4586822Z ##[error]The operation was canceled.
2023-07-17T05:11:04.4603913Z ##[section]Finishing: Run tests (Edge Dev)
```

**Comment by gsnedders** [comment]
@jgraham believes https://github.com/web-platform-tests/wpt/pull/41030 should fix this

it would be good to figure out how we can ensure wptrunner actually exits, though

**Comment by past** [comment]
Lowered the priority since we now keep getting Edge runs frequently.

**Comment by past** [comment]
Sam, should we close this?
