### ISSUE TITLE
Download of chromedriver fails since 115 release

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#41359]
Running WebDriver jobs locally fails downloading the Chromedriver binary:

```
./wpt run chrome webdriver/tests/bidi/script/call_function/arguments.py --channel=nightly         git:(master↑8228|✚1…5
Download and install chromedriver [Y/n]?
Traceback (most recent call last):
  File "/Users/henrik/code/wpt/./wpt", line 10, in <module>
    wpt.main()
  File "/Users/henrik/code/wpt/tools/wpt/wpt.py", line 233, in main
    rv = script(*args, **kwargs)
  File "/Users/henrik/code/wpt/tools/wpt/run.py", line 887, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "/Users/henrik/code/wpt/tools/wpt/run.py", line 860, in setup_wptrunner
    setup_cls.setup(kwargs)
  File "/Users/henrik/code/wpt/tools/wpt/run.py", line 189, in setup
    self.setup_kwargs(kwargs)
  File "/Users/henrik/code/wpt/tools/wpt/run.py", line 375, in setup_kwargs
    webdriver_binary = self.browser.install_webdriver(
  File "/Users/henrik/code/wpt/tools/wpt/browser.py", line 1031, in install_webdriver
    chromedriver_path = self.install_webdriver_by_version(version, dest, revision)
  File "/Users/henrik/code/wpt/tools/wpt/browser.py", line 744, in install_webdriver_by_version
    unzip(get(url).raw, dest)
  File "/Users/henrik/code/wpt/tools/wpt/utils.py", line 106, in get
    resp.raise_for_status()
  File "/Users/henrik/code/wpt/_venv3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Mac_Arm/1148911/chromedriver_mac64.zip
```

The same also happens for stable which is 115. I assume changes as mentioned on https://chromedriver.chromium.org/downloads might be the reason?

@mathiasbynens can one of you please have a look? Thanks.

**Comment by whimboo** [comment]
CC @jgraham, @foolip, @nechaev-chromium

**Comment by mathiasbynens** [comment]
I believe this is #40119. @DanielRyanSmith

**Comment by jrandolf** [comment]
Marking as a dupe for https://github.com/web-platform-tests/wpt/issues/40119
