### ISSUE TITLE
"six.moves" error running any wpt command on Python 3.12

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#42883]
Fresh Windows 11 computer, with Python 3.12.0 installed but not much else.

In PowerShell:

```
PS C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt> python wpt make-hosts-file | Out-File $env:SystemRoot\System32\drivers\etc\hosts -Encoding ascii -Append
Traceback (most recent call last):
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\wpt", line 10, in <module>
    wpt.main()
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\wpt\wpt.py", line 211, in main
    script, parser = import_command(prog, command, props)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\wpt\wpt.py", line 102, in import_command
    mod = __import__(mod_name)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\ci\make_hosts_file.py", line 8, in <module>
    from ..serve.serve import build_config, make_hosts_file
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\serve\__init__.py", line 1, in <module>
    from . import serve  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\serve\serve.py", line 21, in <module>
    from html5lib import html5parser
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\html5parser.py", line 6, in <module>
    from . import _inputstream
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\_inputstream.py", line 4, in <module>
    from six.moves import http_client, urllib
ModuleNotFoundError: No module named 'six.moves'
```

In Git Bash:

```
d@Domenic-White MINGW64 ~/OneDrive - domenic.me/Code/GitHub/web-platform-tests/wpt (details-open-parser)
$ ./wpt serve
Traceback (most recent call last):
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\wpt", line 10, in <module>
    wpt.main()
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\wpt\wpt.py", line 211, in main
    script, parser = import_command(prog, command, props)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\wpt\wpt.py", line 102, in import_command
    mod = __import__(mod_name)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\serve\__init__.py", line 1, in <module>
    from . import serve  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\serve\serve.py", line 21, in <module>
    from html5lib import html5parser
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\html5parser.py", line 6, in <module>
    from . import _inputstream
  File "C:\Users\d\OneDrive - domenic.me\Code\GitHub\web-platform-tests\wpt\tools\third_party\html5lib\html5lib\_inputstream.py", line 4, in <module>
    from six.moves import http_client, urllib
ModuleNotFoundError: No module named 'six.moves'
```

Do I have to do something to install `six` globally, or something? I didn't see anything in https://web-platform-tests.org/running-tests/from-local-system.html#system-setup .

`C:\Users\d\AppData\Local\Programs\Python\Python312\Scripts\` and its parent directory are in my %PATH%.

**Comment by gsnedders** [comment]
We vendor six 1.15, some of the backwards incompatible changes in Python 3.12 mean we need to upgrade our vendored copy to 1.16 (c.f. https://github.com/benjaminp/six/pull/343 and https://github.com/benjaminp/six/pull/352).
