### ISSUE TITLE
Firefox Android runs are missing browser_version

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#43090]
[This commit](https://github.com/web-platform-tests/wpt/commit/c359284745e2a2f6c44af320d1d6c43ce51f25bc) had successful firefox_android runs, but there are no results in [wpt.fyi](https://wpt.fyi/runs?from=2023-10-31T00%3A00&product=firefox_android). The wpt.fyi logs show that the browser_version field is missing:

```
DEFAULT 2023-11-07T03:26:14Z Traceback (most recent call last): File "/app/wptreport.py", line 441, in sha_product_path self.product_id(separator='-', sanitize=True)) File "/app/wptreport.py", line 397, in product_id self.run_info['browser_version'], KeyError: 'browser_version'
DEFAULT 2023-11-07T03:26:14Z
DEFAULT 2023-11-07T03:26:14Z The above exception was the direct cause of the following exception:
DEFAULT 2023-11-07T03:26:14Z
DEFAULT 2023-11-07T03:26:14Z Traceback (most recent call last): File "/app/processor.py", line 341, in process_report p.report.finalize() File "/app/wptreport.py", line 510, in finalize self.sha_product_path File "/app/wptreport.py", line 444, in sha_product_path raise MissingMetadataError(str(e)) from e wptreport.MissingMetadataError: Missing required metadata ''browser_version'' (['https://community-tc.services.mozilla.com/api/queue/v1/task/JudcVyITTu-E1D44cvYqfw/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/DlFlmpNAQDG2gmGDZCDHMg/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/dXP2jPIWQ2G3OFKkJmiNhg/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/JZMUO8o3SseH9HWkQzbaLQ/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/I2PFR9ZiSeyBsRKyL6LwhQ/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/EBPuKZ6TTBC3coDUKSfLWw/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/fTjtAh1uSn28BMqL1dk68g/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/DATG7lEMQ_CT802KFH05ew/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/HxLQtV2uS7yJSdOVPJPrxg/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/FFWF-PU5S2y6EBidkjsKkw/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/dk4ujtc0Q--9MRlQrQT9BA/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/dh-6lUqDQAOSo1uBNDB6mg/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/XSnWNM0ZT9mffFFNaDRwDQ/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/JTh5R92qQ3KV-IPtEz1sAA/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/DLSxKQ1ITjOhzwbVw9uCHw/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/api/queue/v1/task/S9rB6WSWQYKW0FrgKzFTAg/artifacts/public/results/wpt_report.json.gz', 'https://community-tc.services.mozilla.com/ap…
DEFAULT 2023-11-07T03:26:14Z ERROR:processor:Cannot update status for run 6319550376706048: 500 Server Error: Internal Server Error for url: https://rev-388a0071-dot-wptdashboard.uc.r.appspot.com/api/status/6319550376706048
```

Manually inspecting the [first report](https://community-tc.services.mozilla.com/api/queue/v1/task/JudcVyITTu-E1D44cvYqfw/artifacts/public/results/wpt_report.json.gz) confirms that there is no such field there. 

I see that [run_info_extras for Firefox](https://github.com/web-platform-tests/wpt/blob/9fd8dd44cc8eb0e0b9c71a9e957d9171e8daac77/tools/wptrunner/wptrunner/browsers/firefox.py#L218) takes care of it, whereas [run_info_extras for firefox_android](https://github.com/web-platform-tests/wpt/blob/9fd8dd44cc8eb0e0b9c71a9e957d9171e8daac77/tools/wptrunner/wptrunner/browsers/firefox_android.py#L95) does not.

/CC @jgraham

**Comment by jgraham** [comment]
This bug should now be fixed. I got one trigger run to upload to wpt.fyi, but since then there has been an emulator update that broke everything (and I need to revert), plus some stability issues which meant we didn't get a complete run on master before that update.
