### ISSUE TITLE
"wpt /trusted-types/block-string-assignment-to-attribute-via-attribute-node.html" passes at <wpt.fyi> but fails locally

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [web-platform-tests/wpt#44348]
https://wpt.fyi/results/trusted-types/block-string-assignment-to-attribute-via-attribute-node.html?label=experimental&label=master&aligned shows it passes and that is passes since Nov 26th last year.

Locally, on Ubuntu 22.04, with the current Chrome Dev edition, it fails when running http://wpt.live/trusted-types/block-string-assignment-to-attribute-via-attribute-node.html. Also when ran with
```bash
google-chrome-unstable --enable-experimental-web-platform-features
```
Devtool's console logged:
```
GET https://wpt.live/trusted-types/x net::ERR_ABORTED 404 (Not Found)
8This document requires 'TrustedScriptURL' assignment.
block-string-assignment-to-attribute-via-attribute-node.html:31 This document requires 'TrustedHTML' assignment.
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:31
assert_throws_js_impl @ testharness.js:2084
assert_throws_js @ testharness.js:2071
assert_wrapper @ testharness.js:1463
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:30
Test.step @ testharness.js:2622
test @ testharness.js:633
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:29
block-string-assignment-to-attribute-via-attribute-node.html:36 This document requires 'TrustedHTML' assignment.
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:36
assert_throws_js_impl @ testharness.js:2084
assert_throws_js @ testharness.js:2071
assert_wrapper @ testharness.js:1463
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:35
Test.step @ testharness.js:2622
test @ testharness.js:633
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:34
block-string-assignment-to-attribute-via-attribute-node.html:31 This document requires 'TrustedScript' assignment.
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:31
assert_throws_js_impl @ testharness.js:2084
assert_throws_js @ testharness.js:2071
assert_wrapper @ testharness.js:1463
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:30
Test.step @ testharness.js:2622
test @ testharness.js:633
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:29
block-string-assignment-to-attribute-via-attribute-node.html:36 This document requires 'TrustedScript' assignment.
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:36
assert_throws_js_impl @ testharness.js:2084
assert_throws_js @ testharness.js:2071
assert_wrapper @ testharness.js:1463
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:35
Test.step @ testharness.js:2622
test @ testharness.js:633
(anonymous) @ block-string-assignment-to-attribute-via-attribute-node.html:34
block-string-assignment-to-attribute-via-attribute-node.html:13 
        
        
       GET https://wpt.live/trusted-types/x 404 (Not Found)
testharness.js:4507 This document requires 'TrustedScript' assignment.
make_dom_single @ testharness.js:4507
make_dom @ testharness.js:4527
make_dom_single @ testharness.js:4512
make_dom @ testharness.js:4527
make_dom_single @ testharness.js:4512
make_dom @ testharness.js:4527
render @ testharness.js:4537
Output.show_results @ testharness.js:4231
(anonymous) @ testharness.js:189
(anonymous) @ testharness.js:3816
forEach @ testharness.js:4663
Tests.notify_complete @ testharness.js:3813
all_complete @ testharness.js:3679
Tests.complete @ testharness.js:3691
(anonymous) @ testharness.js:97
setTimeout (async)
(anonymous) @ testharness.js:94
load (async)
on_event @ testharness.js:1201
WindowTestEnvironment @ testharness.js:93
create_test_environment @ testharness.js:525
(anonymous) @ testharness.js:556
(anonymous) @ testharness.js:4974
testharness.js:4507 
        
       Uncaught TypeError: Failed to execute 'setAttribute' on 'Element': This document requires 'TrustedScript' assignment.
    at make_dom_single (testharness.js:4507:29)
    at make_dom (testharness.js:4527:20)
    at make_dom_single (testharness.js:4512:39)
    at make_dom (testharness.js:4527:20)
    at make_dom_single (testharness.js:4512:39)
    at make_dom (testharness.js:4527:20)
    at render (testharness.js:4537:16)
    at Output.show_results (testharness.js:4231:25)
    at testharness.js:189:37
    at testharness.js:3816:22
make_dom_single @ testharness.js:4507
make_dom @ testharness.js:4527
make_dom_single @ testharness.js:4512
make_dom @ testharness.js:4527
make_dom_single @ testharness.js:4512
make_dom @ testharness.js:4527
render @ testharness.js:4537
Output.show_results @ testharness.js:4231
(anonymous) @ testharness.js:189
(anonymous) @ testharness.js:3816
forEach @ testharness.js:4663
Tests.notify_complete @ testharness.js:3813
all_complete @ testharness.js:3679
Tests.complete @ testharness.js:3691
(anonymous) @ testharness.js:97
setTimeout (async)
(anonymous) @ testharness.js:94
load (async)
on_event @ testharness.js:1201
WindowTestEnvironment @ testharness.js:93
create_test_environment @ testharness.js:525
(anonymous) @ testharness.js:556
(anonymous) @ testharness.js:4974
```

Other tests like https://wpt.live/trusted-types/block-string-assignment-to-Element-setAttribute.html pass locally.

**Comment by Ms2ger** [comment]
The test doesn't fail, per se, but testharness.js tries to do some DOM manipulation after completion that throws given the CSP setup that we're testing. In particular, `dump_test_results` creates a `script` with the results, and `Output.prototype.show_results` creates a "Rerun" button I'd never noticed before with an `onclick` attribute (from #29804).

**Comment by Ms2ger** [comment]
cc @jgraham

**Comment by mbrodesser-Igalia** [comment]
This is presumably the same issue as https://github.com/web-platform-tests/wpt/issues/44352, which contains a smaller example.

**Comment by fred-wang** [comment]
Is this issue still valid? Opening http://wpt.live/trusted-types/block-string-assignment-to-attribute-via-attribute-node.html in chromium locally the tests are passing for me.

**Comment by mbrodesser-Igalia** [comment]
Fixed, see https://github.com/web-platform-tests/wpt/issues/44352#issuecomment-2288181277.
