### ISSUE TITLE
`assert_throws_js` fails for an element adopted from an iframe

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [web-platform-tests/wpt#45405]
Example:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      http-equiv="Content-Security-Policy"
      content="require-trusted-types-for 'script';"
    />
    <script src="/resources/testharness.js"></script>
    <script src="/resources/testharnessreport.js"></script>
  </head>
  <body>
    <iframe id="otherIframe"></iframe>
    <script>
      const passThroughPolicy = trustedTypes.createPolicy("passThrough", {
        createHTML: (s) => s,
      });

      async_test((t) => {
        const sourceFrame = document.createElement("iframe");

        sourceFrame.srcdoc = passThroughPolicy.createHTML(
          `<!DOCTYPE html>
            <head>
            <meta charset="utf-8">
            </head>
            <body><iframe srcdoc="v">
            doc without TT CSP.
            </body>`
        );

        sourceFrame.addEventListener(
          "load",
          t.step_func_done(() => {
            const sourceElement =
              sourceFrame.contentDocument.body.querySelector("iframe");
            const sourceAttr = sourceElement.getAttributeNode("srcdoc");
            sourceElement.removeAttributeNode(sourceAttr);

            document.body.append(sourceElement);

            assert_throws_js(TypeError, () => {
              // This should throw because trusted types are enabled.
              document.body.otherIframe.setAttributeNode(sourceAttr);
            }); // works

            assert_throws_js(TypeError, () => {
              // This should throw because trusted types are enabled.
              sourceElement.setAttributeNode(sourceAttr);
            }); // fails
          })
        );

        document.body.append(sourceFrame);
      }, `x`);
    </script>
  </body>
</html>
```

Error log:
```
Unexpected subtest result in /trusted-types/x.html:
  │ FAIL [expected PASS] x
  │   → assert_throws_js: function "() => {
              // This should throw because trusted types are enabled.
              sourceElement.setAttributeNode(sourceAttr);
            }" threw object "TypeError: Failed to execute 'setAttributeNode' on 'Element': This document requires 'TrustedHTML' assignment." ("TypeError") expected instance of function "function TypeError() { [native code] }" ("TypeError")
  │ 
  │     at Test.<anonymous> (http://web-platform.test:8000/trusted-types/x.html:47:13)
  │     at Test.step (http://web-platform.test:8000/resources/testharness.js:2622:25)
  └     at HTMLIFrameElement.<anonymous> (http://web-platform.test:8000/resources/testharness.js:2697:32)

  [1/1] No tests running.
```

Reproducible with Chrome; Firefox doesn't support Trusted Types yet.

The failure stems from https://searchfox.org/mozilla-central/rev/b4860b54810539f0e4ab1fc46a3246daf2428439/testing/web-platform/tests/resources/testharness.js#2122.

CC @lukewarlow

**Comment by mbrodesser-Igalia** [comment]
When debugging this, be aware that https://github.com/web-platform-tests/wpt/issues/44352 will prevent the above error log.

**Comment by mbrodesser-Igalia** [comment]
Adding 
```js
      console.log(
        "(e.constructor === constructor)=" + (e.constructor === constructor)
      );
      console.log("(e instanceof TypeError)=" + (e instanceof TypeError));
      console.log("e.constructor.name=" + e.constructor.name);
```
to https://searchfox.org/mozilla-central/rev/b4860b54810539f0e4ab1fc46a3246daf2428439/testing/web-platform/tests/resources/testharness.js#2122 reveals:

```
 "(e.constructor === constructor)=true", source: http://web-platform.test:8000/resources/testharness.js (2408)
 "(e instanceof TypeError)=true", source: http://web-platform.test:8000/resources/testharness.js (2411)
 "e.constructor.name=TypeError", source: http://web-platform.test:8000/resources/testharness.js (2412)

 "(e.constructor === constructor)=false", source: http://web-platform.test:8000/resources/testharness.js (2408)
 "(e instanceof TypeError)=false", source: http://web-platform.test:8000/resources/testharness.js (2411)
 "e.constructor.name=TypeError", source: http://web-platform.test:8000/resources/testharness.js (2412)
```

**Comment by ptomato** [comment]
It may be relevant for you, test262 takes this case into account in its `assert.throws()` function with a specific error message: https://github.com/tc39/test262/blob/837def66ac1700ce398df4a3b4eaeea915aa1df5/harness/assert.js#L87-L94

**Comment by Ms2ger** [comment]
This is unsurprising, yeah. Use `otherIframe.contentWindow.TypeError` or something like that

**Comment by mbrodesser-Igalia** [comment]
> This is unsurprising, yeah. Use `otherIframe.contentWindow.TypeError` or something like that

@Ms2ger: please explain why it's unsurprising. It's not obvious.

Using
```
assert_throws_js(otherIframe.contentWindow.TypeError, () => {
              // This should throw because trusted types are enabled.
              sourceElement.setAttributeNode(sourceAttr);
            }); // fails
```
still fails.

**Comment by mbrodesser-Igalia** [comment]
```
assert_throws_js(sourceFrame.contentWindow.TypeError
```
works.

**Comment by mbrodesser-Igalia** [comment]
Admittedly, I still don't understand why so would be happy to learn about it.

**Comment by Ms2ger** [comment]
Every realm has its own set of intrinsics, including `TypeError`, and JavaScript does not go behind the scenes to match those up when you do `instanceof`. So if you have
```
error from page A → TypeError from page A
error from page B → TypeError from page B
```
you should by default not assume there's a connection between `error from page A` and `TypeError from page B`. I hope that clarifies a bit.

**Comment by mbrodesser-Igalia** [comment]
> Every realm has its own set of intrinsics, including `TypeError`, and JavaScript does not go behind the scenes to match those up when you do `instanceof`. So if you have
> 
> ```
> error from page A → TypeError from page A
> error from page B → TypeError from page B
> ```
> 
> you should by default not assume there's a connection between `error from page A` and `TypeError from page B`. I hope that clarifies a bit.

@Ms2ger: a bit. None of the documentation I read implied that, or I was unable to deduce those implications.

**Comment by fred-wang** [comment]
cc @lukewarlow 

I've reduced @mbrodesser-Igalia 's original test case to make it clearer:

```html
<!DOCTYPE html>
<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script';"/>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<div id="divInsertedByParser"></div>
<script>
  promise_test(async t => {
    const iframe = document.createElement("iframe");
    const passThroughPolicy = trustedTypes.createPolicy("passThrough", { createHTML: s => s, });
    iframe.srcdoc = passThroughPolicy.createHTML("<!DOCTYPE html><div></div>");
    await new Promise(resolve => {
      iframe.addEventListener("load", resolve);
      document.body.appendChild(iframe);
    });
    const divAdoptedFromIframe = document.adoptNode(iframe.contentDocument.body.firstElementChild);
    assert_throws_js(TypeError, _ => divInsertedByParser.innerHTML = 'unsafe');
    assert_throws_js(TypeError, _ => divAdoptedFromIframe.innerHTML = 'unsafe');
  });
</script>
```

When running assertions, both divInsertedByParser and divAdoptedFromIframe belong to the main document, so the `TypeError` thrown is from the main document's realm. That's the case in Firefox but in WebKit/Chromium the TypeError for divAdoptedFromIframe comes from the iframe document's realm.

**Comment by smaug----** [comment]
Actually, I wonder if it is defined very well, what is the relevant global object for a node which has been adopted.
Maybe it is and Firefox isn't right here.

**Comment by Ms2ger** [comment]
https://webidl.spec.whatwg.org/#js-creating-throwing-exceptions says to use the current realm, as far as I can tell

**Comment by smaug----** [comment]
Ah, good point.

**Comment by otherdaniel** [comment]
> https://webidl.spec.whatwg.org/#js-creating-throwing-exceptions says to use the current realm, as far as I can tell

Yes, but ECMAscript, specifically [§9.4 Execution Contexts](https://tc39.es/ecma262/#sec-execution-contexts), says, _"A new execution context is created whenever control is transferred from the executable code associated with the currently running execution context to executable code that is not associated with that execution context. The newly created execution context is pushed onto the stack and becomes the running execution context."_ 

I read that as saying that when `divAdoptedFromIframe.innerHTML` is a executed in `require-trusted-types-for-TypeError-belongs-to-the-global-object-realm.html`, then the current execution context is the one from `divAdoptedFromIframe`, and the current execution context's realm is then that of `divAdoptedFromIframe` as well. And since `document.adoptNode` doesn't say anything about changing the adopted's node's realm, that would be the realm in which `divAdoptedFromIframe` was originally created.

Admittedly, I'm having an exceedingly hard time parsing the relevant specs. But by my reading, the behaviour expected by the current test version isn't what's actually specified.

This doesn't seem to be a TT-specific issue; we merely stumble over it. E.g. we can easily [adapt the test to not use TT at all](https://github.com/web-platform-tests/wpt/pull/54355/files) and still the same difference shows. The given test passes on Blink + WebKit; but not Firefox. (Note that the test condition here is reversed; it expects different realms. The important bit being the observable behavioural difference.)

It's unclear to me what the intent here is. I take it, this is really about `adoptNode` behaviour. And `adoptNode` was probably specified and implemented before the concept of realms was introduced in JS. So this might be intentional; or it might not.

**Comment by fred-wang** [comment]
So I asked with @nicolo-ribaudo and he commented the realm that matters is not a property of the node, it's a property of the method that is throwing:

```js
function getInnerHTMLSetter(global) {
  return Object.getOwnPropertyDescriptor(global.Element.prototype, "innerHTML").set;
}

const mainNode = document.querySelector("div");
const iframe = document.querySelector("iframe");
const iframeNode = iframe.contentDocument.querySelector("div")

const mainSetInnerHTML = getInnerHTMLSetter(window);
const iframeSetInnerHTML = getInnerHTMLSetter(iframe.contentWindow);

mainSetInnerHTML.call(mainNode, "foo"); // throws TypeError from main
mainSetInnerHTML.call(iframeNode, "foo"); // throws TypeError from main

iframeSetInnerHTML.call(mainNode, "foo"); // throws TypeError from iframe
iframeSetInnerHTML.call(iframeNode, "foo"); // throws TypeError from iframe
```


So @smaug---- 's comment is relevant here: https://github.com/web-platform-tests/wpt/issues/45405#issuecomment-2690489610 ; here is a testcase showing unexpected prototype change in Firefox:

```html
<!DOCTYPE html>
<div id="divInsertedByParser"></div>
<script>
  const iframe = document.createElement("iframe");
  iframe.srcdoc = "<!DOCTYPE html><div></div>";
  iframe.addEventListener("load", _ => {
    const iframeDiv = iframe.contentDocument.body.firstElementChild;
    console.log(iframeDiv instanceof window.HTMLDivElement);
    console.log(iframeDiv instanceof iframe.contentWindow.HTMLDivElement);
    const adoptedDiv = document.adoptNode(iframeDiv);
    console.log(adoptedDiv instanceof window.HTMLDivElement);
    console.log(adoptedDiv instanceof iframe.contentWindow.HTMLDivElement);
  });
  document.body.appendChild(iframe);
</script>
```

The following patch allows to work around Firefox's bug and make the test pass in all browsers:

```diff
diff --git a/trusted-types/Element-setAttribute-respects-Elements-node-documents-globals-CSP-after-adoption-from-non-TT-realm.html b/trusted-types/Element-setAttribute-respects-Elements-node-documents-globals-CSP-after-adoption-from-non-TT-realm.html
index 9f9f8b5ad01a..6c9354aaeb90 100644
--- a/trusted-types/Element-setAttribute-respects-Elements-node-documents-globals-CSP-after-adoption-from-non-TT-realm.html
+++ b/trusted-types/Element-setAttribute-respects-Elements-node-documents-globals-CSP-after-adoption-from-non-TT-realm.html
@@ -25,6 +25,7 @@
     <script>
       const passThroughPolicy = trustedTypes.createPolicy("passThrough", {
         createHTML: (s) => s,
+        createScript: s => s,
       });
 
       function runTest(aTestElement) {
@@ -111,10 +112,11 @@
                 // invokes <https://www.w3.org/TR/trusted-types/#validate-attribute-mutation>.
                 // The latter should throw when executing step 5.
 
-                assert_throws_js(TypeError, () => {
+                let expectedTypeError = new sourceElement.constructor.constructor(passThroughPolicy.createScript("return TypeError"))();
+                assert_throws_js(expectedTypeError, () => {
                   sourceElement.setAttributeNode(sourceAttr);
                 });
-                assert_throws_js(TypeError, () => {
+                assert_throws_js(expectedTypeError, () => {
                   sourceElement.setAttributeNS(
                     sourceAttr.namespaceURI,
                     sourceAttr.name,
```
