### ISSUE TITLE
Chromium pinned version is still at 1206981

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#46980]
The  update-chromium-revision cloud function is failing and has been failing for many months:
```
2024-07-03 04:00:04.772 PDT
update-chromium-revision0kihydoom4j3 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 76, in main
    tests_passed = all_passing_checks()
  File "/workspace/main.py", line 25, in all_passing_checks
    for check in check_info["check_suites"]:
KeyError: 'check_suites' 
```

**Comment by past** [comment]
The actual response is:
```json
{'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest', 'status': '401'}
```

**Comment by past** [comment]
/CC @DanielRyanSmith. I can't confirm whether the GCF secret is properly configured on GitHub.

**Comment by past** [comment]
I added some error logging to the cloud function, for easier debugging in the future.

**Comment by DanielRyanSmith** [comment]
This required an access token refresh on my part and has now been mitigated, and I've added monitoring alerts in case we receive errors concerning the cloud function that runs the pinning logic daily. However, there are still steps that should be taken allow anyone on the team to update the access token.

**Comment by past** [comment]
Thanks for the quick fix! Resolving this specific issue and let's plan for the follow up work mentioned above.
