### ISSUE TITLE
`wpt` fails on stock OS X

### ISSUE THREAD

**Issue by shs96c** [web-platform-tests/wpt#6788]
Steps to reproduce:

```
brew install nss
PATH=/usr/local/opt/nss/bin:$PATH ./wpt run --binary /Applications/Firefox.app/Contents/MacOS/firefox firefox /webdriver
```

Using stock OS X (10.12.6). The following stacktrace is seen:

```
Using certutil /usr/local/opt/nss/bin/certutil
Using webdriver binary /Users/simons/src/web-platform-tests/_venv/bin/geckodriver
Downloading gecko prefs
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/simons/src/web-platform-tests/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/Users/simons/src/web-platform-tests/tools/wpt/run.py", line 341, in run
    **kwargs)
  File "/Users/simons/src/web-platform-tests/tools/wpt/run.py", line 321, in setup_wptrunner
    setup_cls.setup(kwargs)
  File "/Users/simons/src/web-platform-tests/tools/wpt/run.py", line 141, in setup
    self.setup_kwargs(kwargs)
  File "/Users/simons/src/web-platform-tests/tools/wpt/run.py", line 209, in setup_kwargs
    prefs_root = self.browser.install_prefs(self.venv.path)
  File "/Users/simons/src/web-platform-tests/tools/wpt/browser.py", line 158, in install_prefs
    resp = get("https://hg.mozilla.org/mozilla-central/raw-file/tip/testing/profiles/prefs_general.js")
  File "/Users/simons/src/web-platform-tests/tools/wpt/utils.py", line 111, in get
    resp = requests.get(url, stream=True)
  File "/Users/simons/src/web-platform-tests/_venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/simons/src/web-platform-tests/_venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/simons/src/web-platform-tests/_venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/simons/src/web-platform-tests/_venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/simons/src/web-platform-tests/_venv/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='hg.mozilla.org', port=443): Max retries exceeded with url: /mozilla-central/raw-file/tip/testing/profiles/prefs_general.js (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'),))
```

One [suggestion](https://github.com/requests/requests/issues/2022#issuecomment-41475570) is that this is caused by OS X's OpenSSL implementation, but this seems to be okay. The output of `openssl s_client -connect hg.mozilla.org:443` is:

```
CONNECTED(00000003)
depth=1 /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/CN=hg.mozilla.org
   i:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
 1 s:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFHjCCBAagAwIBAgIQA3YLpfJA4nfRaDWib9utoDANBgkqhkiG9w0BAQsFADBN
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5E
aWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTYwODI5MDAwMDAwWhcN
MTgxMTAyMTIwMDAwWjBwMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5p
YTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEbMBkGA1UEChMSTW96aWxsYSBGb3Vu
ZGF0aW9uMRcwFQYDVQQDEw5oZy5tb3ppbGxhLm9yZzCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALsbPbdSvpVa0GBflKY0j2FxImtD75u/NFcvvnXrAEc/
6EUFHwO0sE4WocUFF4PziRgRaJT4vhc0JwwrrhHLo7phLRHxZbjCUqstyNC/7KJw
smQlyom0LhyI8AXRx2dR6FAw82OErn7TMjzaBdoRMmwLKSyfuXSvG8tmly0wPKGE
caK3QD45ZQXp5Q+7LFRe90zAGmIh9W+uN+WZezM+AB/iuotfIb3Kg6qof7O5bK3S
sRmsyR2yv53PB22TSkiXvadoKjsx47Hk/Zr3xscYUxr6BTGW2XasJ1P+/ytnOgmE
PzlbD9/vivQMJod2kPxeocOhs5+1hqbqHuTVmGETkuUCAwEAAaOCAdUwggHRMB8G
A1UdIwQYMBaAFA+AYRyCMWHVLyjnjUY4tCzhxtniMB0GA1UdDgQWBBRPfwRhfoy0
IWmyL8YPZkQybIaJCzAZBgNVHREEEjAQgg5oZy5tb3ppbGxhLm9yZzAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGsGA1UdHwRk
MGIwL6AtoCuGKWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9zc2NhLXNoYTItZzUu
Y3JsMC+gLaArhilodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc3NjYS1zaGEyLWc1
LmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgGCCsGAQUFBwIBFhxodHRw
czovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAECAjB8BggrBgEFBQcBAQRw
MG4wJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBGBggrBgEF
BQcwAoY6aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMlNl
Y3VyZVNlcnZlckNBLmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IB
AQBawKNxIFvKSsBcqW3dchhGzaAIjn2bphIS776TiTZdvEZQEzMZ1860k25UzlKp
x1jTMjBLHR0xUm/L6d58l1Um/rmITUsU7TmITI7279j/kZvsImndWBtguwagRMh3
WFAPB/dzvh675YmYF2wCBMV3gu0rTlx9CdXm5Na2Jlp8g7Qb8DwtctI+j0zAhYEN
EAR9ZvwwMxZu06Y5SjX6/fKLAhiL8SvovysItLWi8CahcQgwILz7SvZ6RAmOVpwh
3upxVj/dEK4G2H+JEUI2UjPRb52iIL4rSw/rao44hyPt2mk9cyQaSLqNbD5hIUQK
JpouSlL019O7dJlZE4xQee3f
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Mountain View/O=Mozilla Foundation/CN=hg.mozilla.org
issuer=/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
---
No client certificate CA names sent
---
SSL handshake has read 3184 bytes and written 320 bytes
---
New, TLSv1/SSLv3, Cipher is EDH-RSA-DES-CBC3-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : EDH-RSA-DES-CBC3-SHA
    Session-ID: 1A0E12AA34F7FFAAAE67FDCDF2FA6C1DBCDCCFE71CE6394491186847F0FC8504
    Session-ID-ctx: 
    Master-Key: E817ACB887396187BE7E264E9947AB2EECFF0EF75008461D8A7947A0073A62201A9A4A65D9E169C61BD576C88BB9E16E
    Key-Arg   : None
    Start Time: 1502272509
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by foolip** [comment]
@shs96c, did you work around this, is it still a problem?

**Comment by foolip** [comment]
I've got `./wpt run` working on a bunch of CI systems in https://github.com/foolip/wpt/pull/5 in macOS that didn't have anything special installed, so I'm closing this. @shs96c, please reopen if you're still having trouble running wpt on a Mac.
